### ISSUE TITLE
Загрузка слайдера.

### ISSUE THREAD

**Issue by dm-grinko** [krambertech/react-essential-course#1]
Катя, у меня такой вопрос. Если я собираюсь прикрутить сторонний слайдер к моему приложению то каким методом реакта мне нужно его оборачивать? этот слайдер по задумке должен получать изображения из массива. Если никак не оборачивать, слайдер срабатывает до того как реакт подгружает к нему изображения из массива. Я хотел использовать owl-carousel слайдер который имеет 2 файла, один сам слайдер, а другой вызов этого слайдера... подскажите как сделать чтобы всё работало.

**Comment by krambertech** [comment]
Привет.

Лучше для этой задачи использовать что-то уже адаптированное для реакт. Вот, например неплохая карусель - [react-slick](https://github.com/akiran/react-slick), вот [демо](http://webrafter.com/opensource/react-slick). 

Использовать он будет приблизительно вот так:

```js
import React from 'react';
import Slider from 'react-slick';

const MySlider = React.createClass({
  render() {
    const settings = {
      // твои настройки
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1
    };

    const images = ['http://www.kinopoisk.ru/images/film_big/333.jpg', 
      'http://www.kinopoisk.ru/images/film_big/338.jpg', 
      'http://www.family-flix.com/wp-content/uploads/2015/06/star-wars-episode-6-return-of-the-jedi.jpg'];

    return (
      <Slider {...settings}>
        {
           images.map(image => 
             <div key={image}><img src={image} /></div>
           )
      }
      </Slider>
    );
  }
});
```

Если я правильно тебя поняла. Если картинки лежат в файлах, можешь использовать `require` для них.

**Comment by dm-grinko** [comment]
спасибо большое, буду пробовать.

**Comment by krambertech** [comment]
Не за что :) Если будут еще вопросы, пиши.

**Comment by maplemap** [comment]
Кто-то сталкивался с динамическим добавлением слайдов?
По типу
```js
<Slider {...settings}>
    <Slide1 />
    <Slide2 />
    <Slide3 />
</Slider>
    );
```

**Comment by maplemap** [comment]
Нашел решение:
```js
const slideComponents = [
    <Slide_1 />,
    <Slide_2 />,
    <Slide_3 />,
    <Slide_4 />
];

<Slider {...sliderSettings}>
    {
        slideComponents.map((slide, index) =>
            <div key={index}>{slide}</div>
        )
    }
</Slider>
```
