### ISSUE TITLE
Webpack - увеличение в размере конечной сборки bundle.js

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#10]
Катерин, привет.

1. Смотрел скринкаст Ильи Кантора по webpack, также собрал собственный по кусочкам, используя тот же скринкаст, твои уроки и интернет. 
Какой ты конфиг webpack'а используешь в живых проектах? Интересует использование в конфиге таких вещей:
 - hot module replacement
 - разделение сборки на 'development' и 'production'
 - делаешь ли ты сборку в классическую модель для 'production', в виде:
<pre>-project
       --css
       --img
       --js
       --index.html
</pre>
 - как поступаешь с изображениями в проекте? Ложишь их в папку ```/public``` или также разделяешь по компонентам?

2. Был ли опыт работы с [React-Bootstrap](https://react-bootstrap.github.io/)?
Если да (но даже если и нет), то может будет у тебя мнение насчет того, почему в проекте с такими зависимостями -
```json
  "dependencies": {
    "bootstrap": "^3.3.6", "(отсюда беру лишь bootstrap.css)"
    "jquery": "*",
    "less": "^2.7.1",
    "react": "^0.14.6",
    "react-bootstrap": "^0.29.5",
    "react-dom": "^0.14.6"
  },
```
происходит разрастание конечного собранного ``` bundle.js ``` в файл размером 1.8Мб в несжатом виде (в сжатом где-то 500Кб). Нормален ли такой объем файла, это при том, что еще не писался кастомный функционал?

**Comment by krambertech** [comment]
**1**

- hmr подключается с помощью react-hot-loader
- да, конфиги обычно делю на dev, prod, иногда еще test
- нет, у меня есть просто папка build
- изображения, которые только в этом компоненте, кладу в папку с ним. Какие-то общие, типа логотипов, кладу в public/static/img

**2**

React-Bootstrap использовала давно когда-то. Не люблю его 😬 

Размер бандла получается очень большой. У меня сейчас на проекте с кучей зависимостей и страниц 250 Кб. 

Ты же смотришь в продакшене? Сорсмапы отключены? Код минифицирован?

**Comment by maplemap** [comment]
Отказался от некоторых зависимостей (от бустрапа в частности), оставил лишь
```json  
"dependencies": {
    "json-loader": "^0.5.4",
    "less": "^2.7.1",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-masonry-component": "^4.0.4",
    "react-slick": "^0.12.2"
  }
```
При сборке для продакшена(с минификацией конечно же) вот что показывает
```
bundle.js     271 kB
```

Интересно, он из ``` devDependencies ``` что-то тянет в себя?

**Comment by krambertech** [comment]
Много, очень много все равно.

![image](https://cloud.githubusercontent.com/assets/10474869/16724066/6487ae28-4759-11e6-9f39-60dadbfe92ae.png)

Так это проект большой, много страниц и зависимостей. 

Что-то не так. Запусти webpack bundle analyzer (https://github.com/robertknight/webpack-bundle-size-analyzer)

**Comment by maplemap** [comment]
Вот такая ситуация, подробнее

**Зависимости**
```js
  "dependencies": {
    "classnames": "^2.2.5",
    "json-loader": "^0.5.4",
    "less": "^2.7.1",
    "react": "^0.14.6",
    "react-dom": "^0.14.6",
    "react-masonry-component": "^4.0.4",
    "react-nl2br": "^0.1.1",
    "react-slick": "^0.12.2",
    "react-waypoint": "^3.0.0"
  },
```

**После запуска webpack --json | webpack-bundle-size-analyzer**
```js
react: 610.88 KB (47.0%)
sockjs-client: 98.54 KB (7.58%)
lodash: 95.9 KB (7.38%)
json3: 42.28 KB (3.25%)
react-slick: 41.13 KB (3.17%)
  object-assign: 484 B (1.15%)
  <self>: 40.66 KB (98.9%)
fbjs: 37.86 KB (2.91%)
url: 36.04 KB (2.77%)
  punycode: 14.31 KB (39.7%)
  <self>: 21.74 KB (60.3%)
outlayer: 35.82 KB (2.76%)
react-proxy: 21.75 KB (1.67%)
react-waypoint: 13.14 KB (1.01%)
url-parse: 9.44 KB (0.726%)
imagesloaded: 9.39 KB (0.723%)
enquire.js: 9.24 KB (0.711%)
debug: 7.67 KB (0.591%)
style-loader: 6.99 KB (0.538%)
masonry-layout: 6.3 KB (0.484%)
react-hot-loader: 5.69 KB (0.438%)
fizzy-ui-utils: 5.65 KB (0.435%)
react-masonry-component: 5.35 KB (0.412%)
get-size: 5.17 KB (0.398%)
querystring: 4.51 KB (0.347%)
webpack: 3.28 KB (0.252%)
process: 2.76 KB (0.212%)
webpack-dev-server: 2.61 KB (0.201%)
ev-emitter: 2.54 KB (0.195%)
ms: 2.28 KB (0.175%)
css-loader: 1.47 KB (0.113%)
querystringify: 1.27 KB (0.0978%)
desandro-matches-selector: 1.27 KB (0.0974%)
json2mq: 1.13 KB (0.0873%)
classnames: 1.08 KB (0.0828%)
react-responsive-mixin: 826 B (0.0621%)
requires-port: 753 B (0.0566%)
inherits: 672 B (0.0505%)
react-nl2br: 429 B (0.0322%)
global: 243 B (0.0183%)
string-convert: 216 B (0.0162%)
strip-ansi: 161 B (0.0121%)
can-use-dom: 139 B (0.0104%)
ansi-regex: 135 B (0.0101%)
react-dom: 63 B (0.00473%)
<self>: 167.52 KB (12.9%)
```

**В браузере**
![screenshot](https://cloud.githubusercontent.com/assets/5664270/16765247/a2ed5978-483b-11e6-934f-ff5781569817.png)

**Comment by lozinsky** [comment]
А вы используете данный плагин?
`plugins: [
	new webpack.DefinePlugin({
		'process.env': {
			NODE_ENV: JSON.stringify('production'),
		},
	}),
],`

**Comment by krambertech** [comment]
я использую cross-env (https://www.npmjs.com/package/cross-env)

**Comment by maplemap** [comment]
@lozinsky, нет, не использую.
Мой webpack.config.js, на всякий случай.
Если у кого-то появятся мысли насчет большого размера сборки, буду признателен.

```js
var webpack = require('webpack');

const NODE_ENV = process.env.NODE_ENV || 'development';
const NODE_HOST = process.env.NODE_HOST || '0.0.0.0';
const NODE_PORT = process.env.NODE_PORT || 8090;

const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: getEntrySources(['./src/main.js']),
    output: {
        path: __dirname + '/public/build',
        publicPath: "/public/",
        filename: "bundle.js"
    },
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: (process.env.NODE_ENV === "production")
                            ? ExtractTextPlugin.extract('style', 'css!autoprefixer')
                            : "style-loader!css-loader!autoprefixer-loader",
                exclude: [/node_modules/, /public/]
            },
            {
                test: /\.less$/,
                loader: (process.env.NODE_ENV === "production") 
                            ? ExtractTextPlugin.extract('style', 'css!less!autoprefixer')
                            : "style-loader!css-loader!autoprefixer-loader!less",
                exclude: [/node_modules/, /public/]
            },
            {
                test: /\.(jpe?g|png|gif|svg|ico)$/i,
                loaders: [
                    'file?name=[sha512:hash:base64:7].[ext]',
                    'image-webpack?progressive=true&optimizationLevel=7&interlaced=true'
                ],
                exclude: [/node_modules/, /public/, /src\/fonts/]
            },
            {
                test   : /\.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
                loader : 'file?name=[name].[ext]',
                exclude: [/node_modules/, /public/, /src\/img/]
            },
            {
                test: /\.json$/,
                loader: "json-loader"
            },
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel',
                query: {
                    presets: ["es2015", "stage-0", "react"],
                    plugins: ["react-hot-loader/babel"]
                }
            }
        ]
    },

    devServer: {
        colors: true,
        historyApiFallback: true,
        inline: false,
        contentBase: __dirname + '/public',
        port: NODE_PORT,
        hot: true
    },

    plugins: [
        new ExtractTextPlugin('bundle.css', {
            allChunks: true, 
            disable: process.env.NODE_ENV == 'development'
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin()
    ]
};

if (NODE_ENV == 'production') {
    module.exports.plugins.push(
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings:     false,
                drop_console: true,
                unsafe:       true
            }
        })
    );
}

function getEntrySources(sources) {
    if (process.env.NODE_ENV !== 'production') {
        sources.unshift('react-hot-loader/patch');
        sources.unshift(`webpack-dev-server/client?http://${NODE_HOST}:${NODE_PORT}`);
        sources.unshift('webpack/hot/only-dev-server');
    }

    return sources;
}
```

**Comment by krambertech** [comment]
В аналайзере ничего необычного вроде нет, хотя весь лодаш тянется, но это не так страшно.

Переменные окружения (`development` и `production`) помогут немного уменьшить билд.

+ там есть еще всякие плагины для бабеля
"transform-react-remove-prop-types",
"transform-react-constant-elements",
 "transform-react-inline-elements"

+ можно с помощью ExtractTextPlugin вынести css в отдельный файл

+ на крайняк, можно загружать js небольшими кусочками, можно такое настроить

**Comment by krambertech** [comment]
Написала уже после того, как ты конфиг скинул

**Comment by maplemap** [comment]
Да, на production так и происходит - с помощью ExtractTextPlugin css выносится в отдельный файл.
Ок, буду отслеживать этот момент. Пока тему закрою. 
Всем спасибо за участие.
