### ISSUE TITLE
Продолжение ...

### ISSUE THREAD

**Issue by h-consul** [krambertech/react-essential-course#11]
Екатерина, добрый день!
Стоит ли ожидать продолжения курса? (5-ое и 6-ое видео).
Если да, то когда примерно они появятся? неделя, месяц?
п.с.
Курсы и правда хороши!!!

**Comment by maplemap** [comment]
Присоединяюсь к вопросу.

**Comment by krambertech** [comment]
@h-consul  @maplemap  5е уже ж есть. 6 будет до конца этого месяца

**Comment by h-consul** [comment]
Вас понял, спасибо большое

**Comment by krambertech** [comment]
Уже почтиии, осталось совсем немного 😬 

Извиняюсь за задержки 😣

**Comment by alukos** [comment]
Катерина, большое спасибо за замечательный курс! 
- Хотел уточнить судьбу 6 урока :)
- Не планируете курс по graphql, relay?
Кроме как из-за вас смысл продлять прописку непонятен ;)

**Comment by krambertech** [comment]
Уже вот-вот :) Сейчас очень много дел рабочих, все никак не домонтирую его. 

По graphql/relay, может, проведу вебинар когда-нибудь (для них подписка не нужна 😉), но я не считаю себя особым специалистом, так игралась немного. 

Скорее всего, буду еще вести более продвинутый офлайн курс по реакту осенью с es6, redux'ом и immutable.

**Comment by krambertech** [comment]
Все! 6 и 7 готовы, скоро ITVDN должен выложить 😊
