### ISSUE TITLE
05-flux

### ISSUE THREAD

**Issue by RomanHristofor** [krambertech/react-essential-course#12]
привет, Катерина.

Вопрос по 5 уроку ( 05-flux ), в частности интересует как вы запускали devserver? Спасибо

**Comment by krambertech** [comment]
```npm run devserver```

саму команду смотри в `package.json` -> `scripts`

**Comment by krambertech** [comment]
вот 

https://github.com/krambertech/react-essential-course/blob/master/05-flux/00-tasks-app/package.json#L8

добавляли в 3м уроке

**Comment by RomanHristofor** [comment]
запустился сервер, спасибо но,
на экране ничего, в консоли: SESSION_AUTHORIZE_FAIL.

в src/api/index.js ( предварительно создал в гугл-апи ключ, все как в уроке ), добавил
его в const CLIENT_ID

**Comment by krambertech** [comment]
Ты там все настроил в Google developer console?

Пришли код ошибки.

**Comment by RomanHristofor** [comment]
хм, странно
![11](https://cloud.githubusercontent.com/assets/10484380/16765414/8f9f2f8a-483c-11e6-857b-94a45786dcce.jpg)

**Comment by RomanHristofor** [comment]
![22](https://cloud.githubusercontent.com/assets/10484380/16765437/baabd836-483c-11e6-9c93-b1ebf39ed137.jpg)

вот скрин с Google developer console

**Comment by krambertech** [comment]
Открой `/login` и нажми кнопку "Войти"

Там не хватает редиректа с `/` на `/login`. Можешь сделать пул-реквест заодно :)

**Comment by RomanHristofor** [comment]
Спасибо, Катя. заработало. 
так контент есть только на стр /login - я верно понимаю?)
остальные страницы надо наполнять?

**Comment by krambertech** [comment]
Да, мы просто на корневой роут (`/`) ничего не положили. Нужно просто добавить `<Redirect />`, добавишь?

**Comment by RomanHristofor** [comment]
если я захотел использовать последнюю material-ui - с реактом уже конфликт.

ps я просто решил немного стилей попытаться добавить на стр / из библ material-ui - но там уже все другое(((

**Comment by RomanHristofor** [comment]
Нужно просто добавить <Redirect />, добавишь?
ну я пока решил эту проблему так:
<Route path='/' component={LoginPage}> // наверно не самый правельный способ

**Comment by RomanHristofor** [comment]
обновил все компоннеты до версии latest. переписал пути.
как вставить кнопку? на кнопке конфликт
импортирую кнопку: `import RaisedButton from 'material-ui/RaisedButton';`

в консоле ошибка:
![121](https://cloud.githubusercontent.com/assets/10484380/16797704/5e3fecb2-48f1-11e6-9dc4-3f2a87e92b15.jpg)

выкинул код: `                        <RaisedButton
                            className='login-button'
                            label='Log in with Google'
                            onClick={this.handleLogIn}
                        />`
все гуд, но без кнопки))
![1](https://cloud.githubusercontent.com/assets/10484380/16797729/7e8bff2e-48f1-11e6-9dfb-8d68deed139a.jpg)

**Comment by krambertech** [comment]
Редирект: https://github.com/reactjs/react-router/blob/master/docs/API.md#redirect

По поводу material-ui почитай у них доку. По поводу кастомизации material-ui - http://www.material-ui.com/#/customization/themes 

Если обновляешь на новый material-ui, то лучше и на 15 реакт перейти.

**Comment by RomanHristofor** [comment]
> Если обновляешь на новый material-ui, то лучше и на 15 реакт перейти.

 я на 15-ом реакте и пробовал это делать.

спасибо за ссылки, Катя)

**Comment by Sergey196970** [comment]
ссылка на <redirect /> должно быть переехала на  https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Redirect.md

**Comment by Sergey196970** [comment]
<<<<Да, мы просто на корневой роут ( /) ничего не положили. Нужно просто добавить <Redirect />, добавишь?>>>>

так как версия react-rout 2,0,0, то для отображения компонента /login нужен не редирект, а использование <IndexRoute component={LoginPage} /> сразу после App роута
