### ISSUE TITLE
React Page Preloader

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#13]
Не знаю, насколько это по тематике учебного курса, но надеюсь, если найдется ответ, он будет многим полезен.
Катерин, не сталкивалась в React с прелоадерами страниц, т.е. мне нужно отображать страницу с анимацией пока грузится вся js-сборка. Если бы еще и процент загрузки можно было бы отслеживать - было бы шикарно.
Есть варианты?

**Comment by krambertech** [comment]
В index.html можно запнуть лоадер прямо в элемент , в который потом будем вставлять наш реакт.

```html
    <div id='content'>
            <div style="background-color: #85D656; display: flex; width: 100vw; height: 100vh;">
                <img src="/static/images/white_logo.png" style="margin: auto; max-width: 100%; width: 300px;">
            </div>
        </div>
```

Например, так. Соответственно, он будет от отображаться пока не загрузится и не запустится скрипт.

**Comment by maplemap** [comment]
Да, твой вариант для лоадера - очень прост и это отлично в определенных случаях.
Я немного имел ввиду другое, более управляемое что-ли.
Пока остановился на следующем коде, правда, не знаю насколько это вяжется с React-Way.

```html
<body onLoad="onLoad();">
//Your loader or animation code


<script>
    function onLoad() {
        var head = document.getElementsByTagName("head")[0];

        var cssBundle = document.createElement("link");
        cssBundle.href = "./build/bundle.css";
        cssBundle.type = "text/css";
        cssBundle.rel = "stylesheet";
        cssBundle.async = true;
        head.appendChild(cssBundle);


        var jsBundle = document.createElement("script");
        jsBundle.src = "./build/bundle.js";
        jsBundle.type = "text/javascript";
        head.appendChild(jsBundle);

        jsBundle.onload = function () {
          //remove loader or animation
        };
    }
</script>
</body>
```
