### ISSUE TITLE
Atom for JS

### ISSUE THREAD

**Issue by marynaToch** [krambertech/react-essential-course#15]
Добрый день, Екатерина. Спасибо большое за Ваши уроки. Вы советуете использовать для написания кода Atom. Почему-то, у меня он не выдает ошибки в JS. Я установила уже целую кучу Packages для него, в том числе и те, что Вы рекомендовали. Ошибки в CSS и HTML работают, а вот в JS - нет. Какие lint мне нужно для этого установить? Уже есть для JS atom-jshint, jshint, jslint, lint, linter, linter-eslint, linter-flow, linter-jscs, linter-jshint ... Не работает ничего. Я новичок в программировании и самоучка, может быть просто что-то не так подключаю? Спасибо заранее!

**Comment by krambertech** [comment]
Добрый день,

А файл .eslintrc у вас есть?

**Comment by maplemap** [comment]
Катерин, если не трудно, можно список packages, которые у тебя установлены в Atom'e?

**Comment by krambertech** [comment]
Часть есть тут: https://github.com/krambertech/react-essential-course#faq

еще:
https://atom.io/packages/change-case
https://atom.io/packages/code-peek
https://atom.io/packages/double-tag
https://atom.io/packages/goto-definition
https://atom.io/packages/sort-lines
https://atom.io/packages/activate-power-mode

**Comment by krambertech** [comment]
ну, и еще:
https://atom.io/packages/todo-show
https://atom.io/packages/auto-update-packages
https://atom.io/packages/atom-beautify
https://atom.io/packages/tool-bar
https://atom.io/packages/atom-ternjs
https://atom.io/packages/editorconfig
https://atom.io/packages/git-projects
https://atom.io/packages/docblockr
https://atom.io/packages/auto-detect-indentation

**Comment by maplemap** [comment]
Супер, спасибо.

**Comment by marynaToch** [comment]
Добрый день, Екатерина! Спасибо большое за ответ. Нет, такого файла не было. До изучения React  я работала в Web Storm, который показывал автоматически все ошибки в JS. Видимо в Ваших уроках я где-то пропустила, что такой файл нужен(((. Я сейчас его создала, но он выдает ошибки только в командной строке при вызове eslint (при этом нужно вызывать его каждый раз). Есть ли возможность настроить его так, чтоб он выдавал ошибки сразу по ходу их выполнения автоматически, прописывая их в Issue например и подчеркивая в самом коде? Какая конфигурация прописана у Вас в этом файлике? Спасибо!

**Comment by krambertech** [comment]
Для начала попробуй использовать како-то готовый конфиг и постепенно будешь его модифицировать под себя. Рекомендую https://www.npmjs.com/package/eslint-config-airbnb

Должны подсвечиваться красиво:

![image](https://cloud.githubusercontent.com/assets/10474869/17587287/00a3330c-5fd0-11e6-917e-0d7969c0bfa0.png)

Попробуй поубирать лишние плагины. Если не поможет, то установи заново. Нашла такой туториал еще - http://www.codeblocq.com/2016/03/Setup-ESLint-in-Atom/

P.S. Ты же открываешь весь проект, а не отдельно файлы?

![image](https://cloud.githubusercontent.com/assets/10474869/17587329/52c7050a-5fd0-11e6-8364-a587978afd34.png)

**Comment by marynaToch** [comment]
Спасибо огромное за помощь! Буду пробовать!

**Comment by rivers-lis** [comment]
Катерина здравствуйте, подскажите пожалуйста снипет react-redux-es6-snippets 0.1.3 можно использовать.
