### ISSUE TITLE
Flux: Получение данных при загрузке

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#16]
Начал рассматривать flux-подход. На первый взгляд он не так прост, но видимо это оправдывается при многократном изменении данных и таком же рендеринге. 
Но как быть в том случае, когда я хочу единожды, к примеру, при загрузке страницы получить данные от апи, отрендерить компонент с ними и все. Неужели и в таком варианте необходимо проходить через вереницу констант и событий? 
Как действовать в таком случае?

**Comment by krambertech** [comment]
Под каждую задачу - свой инструмент. Если все твое приложение заключается в отображении единожды загруженных данных, то никакой флакс не нужен. И нужен ли тогда реакт вообще? 😁

Если есть какая-то динамика (пользователь может что-то делать, переходить, изменять), нужно уже использовать какой-то подход к работе с состоянием, не так важно какой - mvc, flux, redux, mobx, relay и т.д. Но если уже его использовать, то использовать везде, иначе возникнет путаница.

**Comment by maplemap** [comment]
Так или иначе, но в сегодняшних задачах динамика присутствует везде, поэтому реакт нужен, из-за того что весьма удобен и призывает к структурированности.
Но все же, посоветуй пожалуйста, что использовать в случае, когда данные мы получаем с апи при загрузке страницы? Jquery подключать для единственной задачи неохота, нативный ajax громоздкий. 
Axios?

**Comment by krambertech** [comment]
Можно еще использовать [fetch](https://github.com/github/fetch). Ну и axios тоже. Тут решай уже что больше нравится.

**Comment by maplemap** [comment]
Ок, спасибо, Катерин.
