### ISSUE TITLE
React

### ISSUE THREAD

**Issue by IliaOkhre** [krambertech/react-essential-course#17]
Как узнать правильно я решил задание или нет? С чем сверяться?

**Comment by krambertech** [comment]
Бросай ссылку, как будет свободное время гляну. Лучше сделай к себе в репу пул-реквест с заданием, чтобы можно было комментировать

**Comment by krambertech** [comment]
Ну а вообще, единственно правильных решений нет, все можно сделать кучей разных способов. Решение можно считать верным, если оно отвечает требованиям и решает поставленную задачу :)

Решать все задания тут я не хотела, потому что тогда их бы никто не делал 🙂
