### ISSUE TITLE
Message Preview на FLUX

### ISSUE THREAD

**Issue by h-consul** [krambertech/react-essential-course#18]
Екатерина, добрый день!

На днях пытался переделать приложение «Message Preview»! решил переписать его на Flux. Решил использовать API. (нашел в интернете. Просто список товаров с описанием(модель, год, страна, цена и тд)). 

В одном компоненте отображался список товаров. По нажатию на изображение, через ‘push’ бросал его ‘id’ в ‘props.params’.

А во втором компоненте на ‘componentWillMount’ ловил этот ‘id’ (из params) и вызывал Action передавая этот id.

Потом искал товар с этим id во всем списке торов (в store)… получал именно тот товар на который кликал и отображал его.

Все нормально, работает. Кликаю на изображение, справа рендерится второй компонент и отображает подробную информацию.

Только вот проблема. Кликаю на товар в списке, рендерится второй компонент, отображается вся информация! Но если ОБНОВИТЬ СТРАНИЦУ, пропадает не только компонент с «выбранным» товаром, но и сам компонент со всем списком товаров.

Почему, никак понять не могу. Почему пропадает компонент со всем списком товаров, если у него на componentWillMount вызываю action, потом идет запрос к API (api возвращает все товары, потом эти товары рендерятся в этом компоненте). По идеи должен перед рендерингом обращаться к API. И отображать список товаров. Но вот почему при обновлении страницы они пропадают…. Не знаю

**Comment by h-consul** [comment]
разобрался сам))))
спасибо)

**Comment by alukos** [comment]
Мне кажется, хорошим тоном было бы если сам нашел решение посвятить в него всех, кто наткнулся на твой вопрос )

**Comment by h-consul** [comment]
)))))))
Проблема в том, что я принимал из состояния параметр (‘selected product’ - массив объектов) и на основе этого параметра рендерил второй компонент. (использовал ‘map’).

При обновлении страницы, состояние ‘selected product’ пропадало.(т.к. выбранного товара не было). 

Поэтому написал условие….. если параметров нет, то рендери пустую строку (например) ….
А если есть, то рендери нужную мне информацию.
