### ISSUE TITLE
Верстка с react

### ISSUE THREAD

**Issue by alukos** [krambertech/react-essential-course#19]
Катерина, добрый день!
Скажи, пожалуйста, 

1. пользуешься ли чем то для создания сеток вроде [react-grid-layout](https://github.com/STRML/react-grid-layout#responsive-grid-layout-props), [react-layout-components
](https://github.com/rofrischmann/react-layout-components), [react-bem-grid](https://github.com/nordnet/react-bem-grid) или какой то css библиотечкой?

1. пользуешься flexbox? вроде IE его не поддерживает

1. нужно чтобы горизонтальное меню заменялось в мобильной версии на выезжающий бургер с дополнительными пунктами, если делать через медиа запросы нужно оба меню держать в DOM или лучше примонтировать при resize?

1. инлайнишь css внутри компонентов чем то вроде [radium](http://stack.formidable.com/radium/) (как тогда медиа запросы и общие переменные, например, палитру вынести?) или bem в less? 

    1. если по bem, то используешь что то типа [react-bem-helper](https://github.com/marcohamersma/react-bem-helper) или руками в jsx классы целиком  пишешь?

Спасибо

**Comment by krambertech** [comment]
Добрый,

1) Нет, не пользуюсь

2) `flexbox` очень люблю и пользуюсь постоянно. Edge (и частично ИЕ 11) поддерживает, для моих проектов этого достаточно.

3) Не вижу проблемы с тем, чтобы оба были в DOM. CSS медиа запросы будут срабатывать быстрее, чем если сделать это через события window.

4) Я использую, в основном, css-модули сейчас. Если писать css-in-js, то мне больше нравится выносить все-таки стили в отдельный css файл. Вот сравнение разных библиотек - https://github.com/MicheleBertoli/css-in-js

**Comment by alukos** [comment]
А BEM пользуешься? Если да, в jsx классы руками полностью пишешь?

**Comment by krambertech** [comment]
C появлением в моей жизни css модулей, необходимость в БЭМ отпала полностью. Раньше использовала, но проект был не сильно большой, поэтому писала ручками. Ну а так, лучше использовать хелперы, конечно.

**Comment by alukos** [comment]
1.  Ты каким cuss модулем пользуешься? 

1.  Общие стили, например, палитру в отдельный компонент выносишь?

**Comment by krambertech** [comment]
Почитай про css-модули https://github.com/css-modules/css-modules Это как css с локальной областью видимости.

Я пользуюсь препроцессорами, переменные храню в отдельных файлах

**Comment by alukos** [comment]
Спасибо, Катерина, тебе большое  :)
