### ISSUE TITLE
Расширения Chrome

### ISSUE THREAD

**Issue by alukos** [krambertech/react-essential-course#20]
Катерина!
Какими расширениями Хрома ты пользуешься?

**Comment by krambertech** [comment]
Все, что у меня стоят:
- 1Password
- Adblock Plus
- Advanced REST client
- Momentum
- React Developer Tools
- Redux DevTools
- Yet Another Lorem Ipsum Generator
- Pocket
- Todoist

**Comment by alukos** [comment]
Спасибо
