### ISSUE TITLE
Урок 6

### ISSUE THREAD

**Issue by h-consul** [krambertech/react-essential-course#21]
Катя, добрый день!
Пытаюсь переделать способ отображения ‘currentTaskList’ в Заголовке.

Вместо того, чтобы обращаться к API (чтобы получить текущий taskList), решил попробовать отфильтровать весь список taskLists (из store) и найти среди них объект, чей id совпадает с id из ‘props.params.id’ (т.е. текущий). 

В общем нашел и отправил потом этот объект (id, name) в TasksPage-component (через props). Потом получил и отобразил его. 

‘this.props.currentList.name’

В итоге, все нормально отображается. Заголовки меняются мгновенно. Но как только обновляю страницу, получаю ошибку. 

‘TypeError: Cannot read property 'name' of undefined’

(если я правильно понимаю, этот объект не передался еще через ‘props’ и соответственно ‘name’ будет undefined)

С этой проблемой сталкиваюсь достаточно часто. Решаю ее «методом тыка».))  Иногда пишу условие, иногда проверяю пришел ‘props’ или нет. Иногда помогает, иногда нет.

Четкого объяснения этой проблемы у меня нет. Как собственно и решения.)

Можете в вкратце объяснить в чем дело?))
Спасибо

**Comment by krambertech** [comment]
Привет!

> Вместо того, чтобы обращаться к API (чтобы получить текущий taskList), решил попробовать отфильтровать весь список taskLists (из store) и найти среди них объект, чей id совпадает с id из ‘props.params.id’ (т.е. текущий)

Идея правильная.

Проблема объясняется просто. Список элементов тебе еще не пришел, а ты уже пытаешься из него что-то вытащить. Ведь страница рендерится раньше, чем приходит ответ с сервера. Абсолютно логично, ведь ты не можешь отобразить то, чего еще нет 🙂

Можно такие вещи хендлить в методе получения данных в сторе с помощью метода а-ля `getCurrentTaskListName()`. И там, если список еще грузится отдавать пустую строку, например. Или прямо в нужном месте в компоненте `currentTaskList && currentTaskList.name`. Оба варианта имеют право на жизнь :)

Я сейчас использую redux в основном и там это можно делать в методе `mapStateToProps` либо прямо в селекторах (если использовать [reselect](https://github.com/reactjs/reselect), например).

Вообще, очень советую использовать [normalizr](https://github.com/paularmstrong/normalizr). Мне нравится хранить все данные вместе в нормализованном виде. А в в других местах использовать id для их получения. Очень удобно 😉

**Comment by h-consul** [comment]
Точно!!! Нужно попробовать это сделать в 'mapStateToProps')). Как правило, этот метод я использую только в качестве получения конкретного state из store …. и на этом все. Точно)))))
Спасибо, Катя.
И за ‘normalizr’ тоже отдельное спасибо)
Удачи
