### ISSUE TITLE
Добрый день, не могли бы вы помочь с организацией модульности при помощи Gulp?

### ISSUE THREAD

**Issue by CodeLookBook** [krambertech/react-essential-course#22]
Добрый день Катерина, не могли бы вы помочь с организацией модульности при помощи Gulp?

1) Для создания web проекта я использую фреймворк Laravel. Для управления ".jsx" файлами я использую рекомендуемый Laravel пакет Gulp. При помощи него я хотел объединить между собой ".jsx" файлы в один единый файл "main.js".
Проблема в следующем. При моей попытке соединить между собой отдельные ".jsx" файлы с react компонентами в один файл "main.js" ничего не выходит. Я попробовал соединять между собой файлы и при помощи функции require() и при помощи import. Всегда одна и та же ошибка выдается в браузере :  "Uncaught ReferenceError: require is not defined".

2) Нужно ли в целом использовать подключение файлов между собой, если gulp (судя по всему как и webpack) может объединить все компоненты react выделенные в отдельные файлы в один единый файл? Другими словами, компоненты разбитые по отдельным файлам, в итоге ведь все равно смогут обнаружить (увидеть) друг друга после объединения в единый файл (например "main.js").

Извините, если я не совсем точно и понятно сформулировал вопросы. Я просто не слишком часто задаю их, в основном всегда пытаясь найти ответ сам. Но тут что то совсем тяжело.

**Comment by krambertech** [comment]
Привет!

Я давно уже не пользовалась gulp, только webpack в последнее время. Так, Laravel - это php фреймворк. На php я в последний раз писала лет 5 назад и это была форма обратной связи 😁 Пока выходит, что вопрос не совсем по моей части, но я попробую как-то помочь.

1) Ошибка `Uncaught ReferenceError: require is not defined` происходит видимо потому, что ты пытаешься использовать `require` в браузере. В чистом виде так делать не получится. 

2) Обычно все-таки делается один бандл, чтобы запускать все в браузере. Внутри одного файла все работать будет, если несколько, то уже нужно использовать какую-то реализацию модульности. Gulp это умеет делать при соответствующей настройке. Вот [статья](https://tylermcginnis.com/react-js-tutorial-pt-2-building-react-applications-with-gulp-and-browserify-5489228dde99#.c5d6mf5x5) о том, как можно подружить gulp c модулями с помощью Browserify.

Еще я нашла [пример использования react и laravel с webpack](https://github.com/sexyoung/laravel-react-webpack). Может, попробуешь как-то так?

Надеюсь, хоть немного помогла 😊
