### ISSUE TITLE
Вопрос по реализации polling

### ISSUE THREAD

**Issue by pravosleva** [krambertech/react-essential-course#23]
Привет, я новичек. Задался вопросом регулярного получения данных с сервера. На хабре нашел как реализовать polling (частые запросы): в компонент добавляется пара методов:
```
loadNewDataFromServer: function() {
    $.ajax({
      url: this.props.url,
      dataType: 'json',
      cache: false,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(this.props.url, status, err.toString());
      }.bind(this)
    });
  },
componentDidMount: function() {
    this.loadNewDataFromServer();
    setInterval(this.loadNewDataFromServer, this.props.pollInterval);
  }
```
**Вопрос:** Я правильно понимаю, перед удалением компонента из DOM (при переключении внимания пользователя на другой компонент, полностью не зависящий от полученных данных) для экономии трафика нужно прекратить запросы следующим образом:
```
componentWillUnmount(){

    // подскажите, что здесь?

  }
```
Заранее, спасибо.

**Comment by krambertech** [comment]
Привет!

Делать запросы из компонентов - не самая хорошая идея. Лучше такие вещи выносить в flux/redux/redux-saga/что-то другое. 

Но касательно конкретно твоего вопроса:

```js
componentDidMount() {
    this.loadNewDataFromServer();
    
    // мы записываем весь таймер в this, чтобы потом иметь доступ к нему
    this.pollingTimer = setInterval(this.loadNewDataFromServer, this.props.pollInterval);
 }

// ...

componentWillUnmount(){
    // на анмаунт очищаем
    clearInterval(this.pollingTimer);
}
```

Аналогично с https://github.com/krambertech/react-essential-course/blob/master/02-deep-in-components/02-timer/index.html#L30

**Comment by krambertech** [comment]
Но, я серьезно, лучше не делать такие вещи прямо в компонентах 😉

**Comment by pravosleva** [comment]
Я с консолью еще не подружился, чтобы с работать с нодой, галпом и иже с ними... Но спасибо!
