### ISSUE TITLE
Про курсы

### ISSUE THREAD

**Issue by phemistokl** [krambertech/react-essential-course#24]
Здравствуйте, если я ознакомился с React-ом по видеокурсам на вашем сайте, мне имеет смысл проходить онлайн-курс. Узнаю я там что-то новое именно про React.

**Comment by krambertech** [comment]
Здравствуйте,

Видео-курс я бы назвала cкорее вводным, в нем много полезного для старта, но все же он немного уже успел устареть (во front-end'е все очень быстро меняется) и информации для построения реально крупных приложений в нем недостаточно. 

В новом курсе я старалась раскрыть важные аспекты именно создания "real-world" приложений на реакте, проектирования архитектуры, тестирования, работы с данными, всяких тонкостей и т.д. 

Нового вы узнаете точно много и про сам Реакт, и про всю его экосистему. Но, думаю, на первых 2 (или 3) занятиях будет много уже знакомых вещей. И что еще важно - будет проверка всех заданий, ответы на вопросы, практикумы, чат и футболочки в конце 😉

Но решать вам, ведь для старта и в видео-курсе достаточно материала, дальше можно уже самому читать статьи, пробовать писать что-то и разбираться по-немногу со всем. Плюс курса только в экономии времени и нервных клеток 😁

**Comment by alukos** [comment]
А о каком онлайн курсе идёт речь?

**Comment by phemistokl** [comment]
http://frontend-science.com/react/
