### ISSUE TITLE
Просьба помочь разобрать ошибку

### ISSUE THREAD

**Issue by nextgennexia** [krambertech/react-essential-course#25]
Привет! Помоги пожалуйста с ошибкой в 3ем уроке. После встраивания NotesApp webpack не может сбилдить приложение.
![default](https://cloud.githubusercontent.com/assets/9654622/18352105/7d24ea24-75f6-11e6-95cd-0c8384d4545c.PNG)

**Comment by krambertech** [comment]
Залей в какой-то репозитарий, я посмотрю

**Comment by nextgennexia** [comment]
Ссылка на репозитарий https://github.com/nextgennexia/react
Только что попробовал с нуля: взял из твоего репозитария все файлы, установил свежие npm модули - таже ошибка.

**Comment by krambertech** [comment]
Проблема в том, что ты используешь babel 6.* В этой версии кардинально поменялся API.

**Comment by krambertech** [comment]
Нельзя просто так взять и поставить все свежие модули 😂

![image](https://cloud.githubusercontent.com/assets/10474869/18365478/8736c31e-761b-11e6-9a24-23ce03515a66.png)

**Comment by krambertech** [comment]
Если хочешь, чтобы заработало, почитай документацию babel 6.
https://babeljs.io/
https://babeljs.io/docs/setup/

**Comment by nextgennexia** [comment]
Спасибо, буду разбираться!

**Comment by maplemap** [comment]
Была такая ошибка.
Думаю, что дело в пресетах самого бабель лоадера в конфиге вебпака.
Часть кода оттуда.
```js
...
{
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loader: 'babel',
    query: {
        presets: ["es2015", "stage-0", "react"],
        plugins: ["react-hot-loader/babel"]
    }
}
...
```

**Comment by nextgennexia** [comment]
Только что переписал - все работает! Благодарю всех за помощь!!!
