### ISSUE TITLE
Примеры.

### ISSUE THREAD

**Issue by Ravino** [krambertech/react-essential-course#26]
Доброго времени суток, Екатерина!
Нашёл ваши уроки на youtube. Очень заинтересовали, но хотелось бы увидать текстовые примеры кода. Я незрячий и в видео уловил только  малую часть.Ф

**Comment by krambertech** [comment]
Здравствуйте,

Весь код, что я показывала, есть в этом репозитарии. Сделала для вас ссылки:

Урок 1
- [Hello World](https://github.com/krambertech/react-essential-course/tree/master/01-introduction-to-react/00-template)
- [Props](https://github.com/krambertech/react-essential-course/tree/master/01-introduction-to-react/01-using-props)
- [Поиск по контактам](https://github.com/krambertech/react-essential-course/tree/master/01-introduction-to-react/02-contacts-search)

Урок 2
- [Демонстрация жизненного цикла](http://krambertech.github.io/react-essential-course/lifecycle/)
- [Таймер](https://github.com/krambertech/react-essential-course/tree/master/02-deep-in-components/02-timer)
- [Заметки](https://github.com/krambertech/react-essential-course/tree/master/02-deep-in-components/03-notes-app)

Урок 3
- [Сборка](https://github.com/krambertech/react-essential-course/tree/master/03-environment/00-packages-and-build)

Урок 4
- [Примеры на ES2015](https://github.com/krambertech/react-essential-course/tree/master/04-routing-and-es6/01-es6)
- [Приложение для отображения сообщений (react-router)](https://github.com/krambertech/react-essential-course/tree/master/04-routing-and-es6/02-routing)
- [Использование PropTypes](https://github.com/krambertech/react-essential-course/tree/master/04-routing-and-es6/03-proptypes)
- [Использование контеста](https://github.com/krambertech/react-essential-course/tree/master/04-routing-and-es6/04-context)

Урок 5
- [Приложение для работы с задачами](https://github.com/krambertech/react-essential-course/tree/master/05-flux/00-tasks-app)

Урок 6
- [Продолжение](https://github.com/krambertech/react-essential-course/tree/master/06-real-world/00-tasks-app)

Я правильно вас поняла? Или вас какие-то другие примеры интересуют?
