### ISSUE TITLE
Новый 6-и недельный курс

### ISSUE THREAD

**Issue by h-consul** [krambertech/react-essential-course#27]
Катя, добрый день!
Будут ли рассматриваться вопросы связанные с минификацией файлов (js, css) и разделением приложения на production и development
Спасибо

**Comment by krambertech** [comment]
Об этом обязательно :) 

Я планирую один из практикумов вообще посвятить оптимизации производительности. Если успеем, то даже про code splitting в webpack поговорим.

**Comment by krambertech** [comment]
Если хотите на курс, то лучше поспешить, у нас только 2 места осталось 😉

**Comment by alukos** [comment]
Записался, оплатил аж 5 сентября.
Теперь хочется подтверждения оплаты и расписание занятий.
Организатор прям не уловим ни по телефону, ни по мылу :(
