### ISSUE TITLE
Помощь в третьем задании 01-react-essential-course

### ISSUE THREAD

**Issue by Olena377** [krambertech/react-essential-course#28]
Добрый день.
Застряла на третьем задании: "При клике на контакт, он должен разворачиваться (увеличиваться в высоте) и должна отображаться какая-то дополнительная информация о контакте (например, адрес и email). При повторном клике, информация должна сворачиваться.". 
Как достучаться к конкретному контакту в массиве CONTACTS в методе isOpened?

**Comment by krambertech** [comment]
Добрый,

Так как эта информация касается отображения самого контакта (не имеет отношения к отображению списка), то ее логично в самом контакте и хранить. Т.е. в компонент для отображения самого контакта добавить состояние `isOpened`. При клике менять его на противоположное c помощью метода `this.setState`. А в методе `render` компонента проверять значение `this.state.isOpened` и если `true` отображать дополнительную информацию, если `false` - не отображать.

Например:

```js
var Component = React.createClass({
  getInitialState : function() {
    return {
      showHello : false
    };
  },

  handleToggle : function() {
    // при клике значение `this.state.showHello` меняем на противоположное
    this.setState({
      showHello: !this.state.showHello
    });
  },

  render : function() {
    return (
        <div>
            <button  onClick={this.handleToggle}>Toggle</button>
            {this.state.showHello && "Hello!"} // если `true`, то отображаем надпись
        </div>
     );
  }
});
```

**Comment by Olena377** [comment]
Спасибо большое за оперативный ответ, помогло))
