### ISSUE TITLE
2 урок, 1 задание - вопрос по цветам

### ISSUE THREAD

**Issue by trofivan** [krambertech/react-essential-course#29]
Екатерина, спасибо Вам за проделанную работу. Всё очень понятно и доступно.
Есть вопрос по заметкам. Сделал компонент выбора цвета, в нём выбранный цвет помечается галочной (background-image в CSS и checked в input). Но при инициализации приложения не выбран ни один из цветов, хотя в состоянии NoteEditor хранится цвет. Как это исправить?
Вот исходники: https://github.com/trofivan/react-essential-course/tree/master/02-deep-in-components/homework/01
И по основному коду, правильно ли я написал компонент выбора цвета или есть какие-то грубые ошибки?

**Comment by krambertech** [comment]
https://github.com/trofivan/react-essential-course/commit/6e2b44a75b2a505370a27e8145a865c327c8e5e8

оставила комменты

**Comment by trofivan** [comment]
Спасибо большое за оперативные ответы.
