### ISSUE TITLE
React и TypeScript

### ISSUE THREAD

**Issue by terbooter** [krambertech/react-essential-course#30]
Привет.
Есть ли в планах использовать TypeScript для React приложений?

Для сравнения с vanila JS перевел на TS приложение с созданием заметок из 3 урока https://github.com/terbooter/react-app

По ощущениям TS вполне готов для использования с React.
А плюшки самого TypeScript невозможно переоценить!
Чего только стоят подсказки свойств компонент в ИДЕ
![2](https://cloud.githubusercontent.com/assets/429392/19476975/b2055fb8-9544-11e6-99b2-52f0a52d9fc0.jpg)

**Comment by krambertech** [comment]
Привет!

Мне намного больше нравится Flow (https://flowtype.org/) в плане реакта. Он очень круто вписывается во всю экосистему. Я даже планирую Flow в свой курс по реакту включить 😊

Поэтому в планах TypeScript использовать с React точно нет. 

Но спасибо! Посмотрела код - выглядить забавно!

**Comment by krambertech** [comment]
Но подсветка - оч. круто. Посмотрела, для Flow под Atom тоже есть (https://atom.io/packages/flow-ide)

**Comment by terbooter** [comment]
Ух ты. Даже не знал про Flow.
В каком-то смысле это тот же TypeScript, но проще.
Вполне годная штука.
Насколько я понял, TypeScript больше по синтаксису, фичам и задачам, но при этом полностью вмещает в себя множество всех возможностей Flow.

Сравнение основных моментов http://djcordhose.github.io/flow-vs-typescript/flow-typescript-2.html#/
Очень активно продвигают TS для React
https://www.youtube.com/watch?v=9PTa9-PPVAc
https://www.youtube.com/watch?v=9PTa9-PPVAc

Для нас TS это единственный выбор.
vanila JS - уже на средних проектах невозможно поддерживать
Dart - мертворожденный, нельзя подключать JS
Flow - ограничен только проверкой типов, менее распространен чем TS (один только angular2 сильно увеличит распространение TS ), сильно меньше библиотека с определениями чем у TS, хуже поддержка в основных ИДЕ

**Comment by terbooter** [comment]
Забыл сказать спасибо за отличные курсы.
Рекомендую, включить в курс как минимум Flow. Так как вся прелесть React это в разделении сложного приложения на отдельные независимые компоненты и без инструментов которые опишут интерфейс такого компонента теряется часть красоты.

**Comment by krambertech** [comment]
И тебе спасибо :) Я рада, что для тебя было полезно!

**Comment by krambertech** [comment]
По поводу flow подумала и все-таки включила его в свой курс, правда, уже в следующем потоке.
