### ISSUE TITLE
Вопрос по 02-deep-in-components/03-notes-app/

### ISSUE THREAD

**Issue by NeedToken** [krambertech/react-essential-course#32]
Катерина, здравствуйте! Спасибо за уникальный обучающий материал!

Не понимаю что мы делаем(отправляем, принимаем?) этой строкой: 
< NoteEditor onNoteAdd={this.handleNoteAdd}/;   в компонент(/или из него) NoteEditor? 
И как понять вот эту строку : this.props.onNoteAdd(newNote); (передаем в качестве реквизита переменную newNote параметру onNoteAdd ? )

**Comment by trofivan** [comment]
В компонент **_NoteEditor_** передаём через параметр **_onNoteAdd_**  функцию **_this.handleNoteAdd_** (саму функцию, а не результат её выполнения) из текущего компонента. Далее уже в компоненте **_NoteEditor_** при помощи _**this.props.onNoteAdd(newNote)**_ вызываем эту функцию с параметром **_newNote_**.

**Comment by NeedToken** [comment]
Спасибо! очень сложно, буду стараться понять)
