### ISSUE TITLE
jQuery autocomplete

### ISSUE THREAD

**Issue by JanekRoos** [krambertech/react-essential-course#36]
Добрый день, Екатерина Поршнева!
Известен ли Вам поисковик на сайте наподобие jQuery Autocomplete, который имел бы фиксированную шапку и фиксированный подвал?

**Comment by krambertech** [comment]
Привет.

Для реакта есть такие варианты:
https://github.com/reactjs/react-autocomplete
https://github.com/moroshko/react-autosuggest

Если я правильно поняла, что ты имеешь в виду.

**Comment by JanekRoos** [comment]
Добрый вечер, Екатерина!
В этих примерах автокомплита на React в результатах поиска нет фиксированного подвала. Скажи, ты даешь частные уроки по фронт-енду?

**Comment by krambertech** [comment]
Если я правильно понимаю о чем ты, то все достижимо:

https://github.com/reactjs/react-autocomplete/blob/master/examples/custom-menu/app.js#L45

**Comment by krambertech** [comment]
И тут тоже:
https://github.com/moroshko/react-autosuggest#props

Ты можешь их кастомизировать как душе угодно, передавая метод для рендеринга.
