### ISSUE TITLE
Работа с devserver

### ISSUE THREAD

**Issue by N4G1B4T0R** [krambertech/react-essential-course#38]
Привет, 

У меня такой вопрос,почему когда я использую devserver в package.json

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "devserver": "webpack-dev-server --debug --hot --devtool eval-source-map --output-pathinfo --watch --colors --inline --content-base public --port 8090 --host 0.0.0.0"
  }, 

у меня не работает, а когда сменил порт и хост

"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "devserver": "webpack-dev-server --debug --hot --devtool eval-source-map --output-pathinfo --watch --colors --inline --content-base public --port 8080 --host 127.0.0.1"
  },

у меня заработало. Я использую intellij.

**Comment by krambertech** [comment]
Привет,

Скорее всего просто порт был занят чем-то

Как это проверить и остановить процесс на каком-то порту:

```bash
kill $(lsof -t -i:8090)
```
