### ISSUE TITLE
Сборка проектов.

### ISSUE THREAD

**Issue by Maximilian73** [krambertech/react-essential-course#39]
Екатерина, здравствуйте.
Если можно, подскажите, не собирается проект на реакте. При запуске команды webpack или соответствующего ему devserver получаю ошибку в терминале

ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token (6:4)

ReactDOM.render(<NotesApp />,document.getElementById("content"));

Это, как Вы понимаете entry-файл. Указание на символ < перед NotesApp. Грешу на неправильно приготовленный babel. 

В package.json

{
	"name": "notes",
	"version": "1.0.0",
	"description": "Notes Page Application",
	"main": "index.js",
	"scripts": {
		"test": "echo \"Error: no test specified\" && exit 1",
		"devserver": "webpack-dev-server --debug --hot --devtool eval-source-map --output-pathinfo --watch --colors --inline --content-base public --port 8090 --host 0.0.0.0"
	},
	"author": "Max Filatov <imkogroup@gmail.com>",
	"license": "ISC",
	"dependencies": {
		"jquery": "^3.1.1",
		"react": "^15.4.1",
		"react-dom": "^15.4.1"
	},
	"devDependencies": {
		"babel-core": "^6.18.2",
		"babel-loader": "^6.2.8",
		"css-loader": "^0.26.0",
		"file-loader": "^0.9.0",
		"json-loader": "^0.5.4",
		"postcss-loader": "^1.1.1",
		"react-hot-loader": "^3.0.0-beta.6",
		"style-loader": "^0.13.1",
		"url-loader": "^0.5.7",
		"webpack": "^1.13.3",
		"webpack-dev-server": "^1.16.2"
	}
}

В webpack.config.js в разделе модулей -> загрузчиков
	module: {
        loaders: [
            {
                test: /\.js$/,
                loader: "babel-loader",
				exclude: /(node_modules|public)/,
            },
            {
                test: /\.jsx$/,
                loader: "react-hot!babel-loader",
				exclude: /(node_modules|public)/,
            }
        ]
    }
};
Что не так или неправильно указаны библиотеки? Как я понимаю и прочитал на оф. сайте babel, сейчас надо загружать babel-loader, babel-core ( + babel-cli, "babel-preset-es2015", "babel-preset-react", "babel-preset-stage-2" по необходимости). Возможно, что-то неправильно понимаю. На всякий случай, у меня Gentoo-linux, хотя это неважно. Если можно, ответьте на почту, адрес во вставке кода package.json.

Заранее благодарен за ответ.
Филатов Максим.

**Comment by krambertech** [comment]
Привет,

Хм, если babel-preset-react стоит, то должно быть все отлично. Без него JSX е будет парситься. 

Вопрос уже решен? Если да, то расскажи в чем была проблема.
