### ISSUE TITLE
УРОК 1: Введение в React - метод .map

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#4]
Привет, Катерина. Благодарю за уроки!
В нижеприведенном коде, происходит  перебор массива данных. Почему используется именно метод ```.map```,  а не к примеру ```.forEach``` (он, кстати, не работает - я пробовал). Если мы хотим из массива взять элемент и запустить react-компонент, то, по идее, подходит и тот, и тот методы, но по факту это не так. Что я упускаю из виду и каков алгоритм преобразования данных в нижеприведенном методе?
```js 
this.state.displayedContacts.map(function(el) {
    return <Contact
               key={el.id}
               name={el.name}
               phoneNumber={el.phoneNumber}
               image={el.image}
           />;
})
```

**Comment by krambertech** [comment]
Привет :)

Метод **map** не просто перебирает массив. Он для каждого элемента массива возвращиет новый, который возвращает колбек. 

Т.е. он создает новый массив с результатом вызова функции-колбека для каждого элемента.

Например:

```js
var numbers = [1, 3, 5];

var twiceNumbers = numbers.map(x => x * 2); // [ 2, 6, 10 ]
```

*Тут мы для создали массив этих чисел, умноженных на 2. По сути, map берет каждый элемент массива умножает на 2 и возвращает новый массив из результатов.* 

Метод же **forEach** просто запускает функцию-колбек для каждого элемента.

Например:

```js
var numbers = [1, 3, 5];

numbers.forEach(x => alert(x)); // выведет каждый элемент 
```

В данном случае нам нужно не просто перебрать все элементы, а **в соответствие каждому элементу массива** получить React компонент. Поэтому логично использовать map.

Документация map: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by maplemap** [comment]
Благодарю. Roger that!

**Comment by rodnoi7** [comment]
этот код уже в обработчике событий пишем или нужно создать функцию внутри класса?

**Comment by rodnoi7** [comment]
Какая связь между React и JS?
