### ISSUE TITLE
Вопрос прекрасному ront-End разработчику

### ISSUE THREAD

**Issue by nikola166** [krambertech/react-essential-course#42]
На сколько сейчас актуальный данный курс, что изменилось в 15 версии react и что уже в данном курсе устарело?
Заранее спасибо за ответ.

**Comment by krambertech** [comment]
Привет,

С момента записи курса уже прошло больше года, за это время очень много всего поменялось как в самом реакте/бабеле/роутере/вебпаке/экосистеме, так и в моем видении и подходе к разработке и преподаванию и подаче информации. 

Нового в 15 (и выше) реакте очень много. Это все можно почитать тут: https://facebook.github.io/react/blog/ (у них есть статья о каждом крупном релизе). 

В плане основ (1-3 (4) урок) курс не так устарел, нужно только пойти посмотреть документацию и добавить всякие новые штуки / изменить использование некоторых методов. По поводу 5-6 уроков даже не знаю, сам такой подход к управлению состоянием устарел, да и я их считаю неудачными 😬 Мало где сейчас используется Flux в чистом виде. Все же как-то лучше ознакомиться с Flux концептуально (почитать об отличиях от MVC, написать простенький пример), а потом уже углубляться в какую-то из библиотек для управления состоянием - Redux, Mobx (лучше обе).

Хотя, если бы я курс записывала сейчас, то все было бы уже совсем по-другому 😊
