### ISSUE TITLE
Задача про сортировку todo-листа

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [krambertech/react-essential-course#43]
Екатерина,здравствуйте. Не совсем понимаю как нужно решить задачу фильтрации todo листа. Не могли бы подтолкнуть на мысль, а то в ответах других не хочется копаться.

**Comment by krambertech** [comment]
Привет,

По сути у тебя остается тот же список, только тебе нужно показывать не все его элементы. В данном случае в состоянии может лежать массив задач и тип фильтрации, а уже внутри метода рендер вызывать какой-то метод и получать те задачи, которые нужно отобразить. Основной момент тут - не нужно дублировать данные (т.е. делать два массива todos и filteredTodos в состоянии)
