### ISSUE TITLE
form react

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [krambertech/react-essential-course#44]
Привет,Екатерина. Не будет ли у Вас времени глянуть мое небольшое "приложение", а именно обычную формочку. Хотел бы, что бы Вы указали на мои недочеты, которых будет не мало, хотел бы что бы посоветовали что еще можно почитать или может посмотреть толкового после Вашего курса, чтобы дальше расти. Еще хотел бы, чтобы вы подсказали плагины, которые Вы используете для плавности в React (я имею ввиду что-то типа transition в css3). Вот ссылка на репозиторий https://github.com/SergeyWebDeveloper/formReact

**Comment by krambertech** [comment]
Этому ишью почти год и этот репозиторий уже недоступен. С этого делаю вывод, что это уже неактуально :)

Извини, что не ответила вовремя :(
