### ISSUE TITLE
Интернет магазин

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [krambertech/react-essential-course#46]
Катерина,привет. Подскажи,пожалуйста, по поводу интернет магазина, а именно по поводу 4-го пункта, где нужно сделать функционал добавления в корзину. Как это можно сделать, ведь корзина и и кнопка добавления в корзину находятся в разных компонентах?

**Comment by krambertech** [comment]
Если вдруг актуально еще: это можно сделать вынесением состояния наверх и передачей в дочерние компоненты пропсов и колбеков.

![image](https://user-images.githubusercontent.com/10474869/33520997-5d69824a-d7ce-11e7-8895-73349110633a.png)
