### ISSUE TITLE
Вопрос по NodeJS/React

### ISSUE THREAD

**Issue by vafonkin** [krambertech/react-essential-course#47]
Здравствуйте Екатерина,

Немного не по теме, это не проблема, просто не знаю как по другому с Вами связаться.
Есть практический вопрос по Вашим замечательным курсам, как можно с Вами пообщаться голосом? Очень нужно :)

Мой емайл: vadim.afonkin@gmail.com

Спасибо,

Вадим

**Comment by krambertech** [comment]
Здравствуйте,

Я свою почту не скрываю :) k.porshnieva@gmail.com

Лучше свой вопрос опишите пожалуйста в письме.
