### ISSUE TITLE
02-deep-in-components - ToDo list

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#5]
Есть вопросы касательно раздела [02-deep-in-components](https://github.com/krambertech/react-essential-course/tree/master/02-deep-in-components), а конкретно по **to-do list** и **поиску по заметкам**. 
[Код на jsfiddle](https://jsfiddle.net/MapleMap/d5tk78rj/).

1. При поиске или сортировке данных в приложении, происходит полное изменение состояния (state), в котором хранится массив данных,  а также происходит переписывание localStorage. Поэтому на данном этапе необходимо сохранять (не перезаписывая при следующей сортировке) в промежуточной переменной весь массив данных (метод onToDoSort, строка 132). Более того, необходимо еще отслеживать (метод componentDidUpdate, строка 166) запись в localStorage, иначе, если этого не делать, в состоянии сортировки при добавлении новых элементов и следующей перезагрузки страницы, происходит затирание неотсортированных данных.
Насколько такой подход верен, существует ли простой способ отслеживания этого момента? Интуитивно происходит стремление к более понятному и простому, может ли React это предоставить?

2. В **to-do list** приложении при сортировке происходит изменения цвета  шрифта соответствующих пунктов сортировки ``` All New Completed  ```.  Я задал изначальную сортировку (метод componentWillMount, строка 162) и потом производил изменение ее (метод onToDoSort, строка 150) с передачей в соответсвующий компонент (метод render, строка 171). И уже в компоненте, подставляя необходимый стиль (метод render, строка 83), руководил изменением цвета шрифта ``` All New Completed  ```. 
Этот способ также сработал как и решение в предыдущем абзаце, но опять же интуитивно кажется мне весьма запутанным. Существует ли другой подход к решению этой задачи?

**Comment by krambertech** [comment]
Есть несколько замечаний:

1) Необязательно писать закрывающийся тег: `<span></span>` --> `<span />`

2) По поводу форматирования кода рекомендую почитать Airbnb Javascript Style guide (https://github.com/airbnb/javascript). Там есть раздел о Реакт. В таком виде его сложно читать и не работает подсветка в редакторе.

3) В компоненте **ToDoAdd** лучше хранить текст в состоянии, а не пользоваться ref

4) Я так и не поняла, зачем нужна переменная sortCopyTasks. Смотри, можно в state хранить todos и filter. И сделать метод, который из двух этих значений будет отдават тебе нужные задачи. Без никаких переменных.

Типа такого:

```
getVisibleToDos(todos, filter) {
    if (filter === 'COMPLETED') {
       return todos.filter(todo => todo.isCompleted);
   }

   if (filter === 'NEW') {
       return todos.filter(todo => !todo.isCompleted);
   }

   return todos;
}
```

**Comment by krambertech** [comment]
А по форматированию кода почитай, это может казаться неважным, но на самом деле очень важно. Потому что я, когда открыла, сначала несколько минуть просто пыталась разобрать, что там написано 😬

**Comment by maplemap** [comment]
Прошу прощения, что заставил страдать при взгляде на код. (-_-)
Спасибо за отличную идею об избавлении от ненужных переменных. Теперь выглядит замечательно!
Поправил код и перевел в ES6 [в codepen.io](http://codepen.io/maplemap/pen/dXYLWX)
Мои благодарности за поддержку, Катерина!

**Comment by krambertech** [comment]
Круто 👍 

Мне нравится :)

**Comment by trofivan** [comment]
Немного увлёкся и получился такой ToDo List:

- Github: https://github.com/trofivan/react-essential-course/tree/master/02-deep-in-components/homework/04
- Demo: https://jsfiddle.net/trofivan/4715a1rp/

**Comment by N4G1B4T0R** [comment]
@trofivan Ола, я посмотрел твой to-do-list, крутая реализация, только я вот заметил 1 багу. Это когда ты вводишь ничего, оно добавляет таск. Я вот бы добавил валидность для этого ввода или placeholder. Ну это уже твое дело. А так все супер.

**Comment by krambertech** [comment]
@trofivan Еще у меня не работает фильтр "Активные"

Все задачи. Видно, что в списке 3 активные.
![image](https://cloud.githubusercontent.com/assets/10474869/19836980/b310cbfe-9eb8-11e6-846a-ec2fb321bd6a.png)

Но с фильтром ничего нет:
![image](https://cloud.githubusercontent.com/assets/10474869/19836985/cb87d682-9eb8-11e6-8892-aa7dbee7509f.png)

**Comment by krambertech** [comment]
По коду там достаточно много проблем.

1) Использование const и let. Мне не совсем понятна логика. Много мест, где ты используешь let, а можно было бы const. Если значение переменной не меняется - используй const.

2) Выравнивание в JSX. Нужно стараться, чтобы выравнивание везде было одинаковым. Например, я обычно пишу так:

```js
// short
<Cat>Fluffy</Cat>

// longer
<Cat color="grey" hungry>
    Fluffy
</Cat>

// if you have a lot of props
<Cat
    color="grey"
    hungry
    weight={3}
    mood="sleepy"
>
    Fluffy
</Cat>

// one component with a lot of props
<Cat
    color="grey"
    hungry
    weight={3}
    mood="sleepy"
/>

```

3) мне вообще не нравится как у тебя реализована фильтрация. выглядит неочевидно + ты все время передаешь объекты в props. а это все-таки деоптимизация. это можно сделать намного проще.

4) по code-style

почему тут tasks в кавычках?
![image](https://cloud.githubusercontent.com/assets/10474869/19837043/253782f8-9eba-11e6-9d95-8ba4e5903d02.png)

можно просто `setState({ filter });` (ES6 object property shorthand)
![image](https://cloud.githubusercontent.com/assets/10474869/19837057/6c34ade8-9eba-11e6-8cbf-75c1f9c944ed.png)

тут можно использовать оператор ... `[ ...tasks, newTask ]`
![image](https://cloud.githubusercontent.com/assets/10474869/19837065/9ae2bb6c-9eba-11e6-85f3-1903b1cafbf2.png)

колбеки лучше называть с приставкой `on`
![image](https://cloud.githubusercontent.com/assets/10474869/19837080/ede1ed38-9eba-11e6-985c-d8c072845820.png)

почему тут просто не использовать map?
![image](https://cloud.githubusercontent.com/assets/10474869/19837050/3c33aa2c-9eba-11e6-924c-4a40feb60356.png)

тут лучше перенести текст в состояние, а не чистить его прямо в DOM элементе. (не сильно критично)
![image](https://cloud.githubusercontent.com/assets/10474869/19837075/dbb61ce2-9eba-11e6-8ca2-6c3d494b4830.png)

тут тело ф-ции можно не писать вобще
![image](https://cloud.githubusercontent.com/assets/10474869/19837090/4a6ec49a-9ebb-11e6-9d7e-dbb128b028ff.png)

обработчики лучше называть с приставкой `handle`
![image](https://cloud.githubusercontent.com/assets/10474869/19837091/577f657c-9ebb-11e6-9888-bb9c4c26671d.png)

принято ставить пробел перед />, так код намного лучше читается
![image](https://cloud.githubusercontent.com/assets/10474869/19837096/703c3d60-9ebb-11e6-8d18-4544fce87721.png)

колбеки лучше располагать в конце объявления props. так потом код намного проще читать. в тех же целях, многие любят сортировать props по алфавиту (но колбеки все так же в конце)
![image](https://cloud.githubusercontent.com/assets/10474869/19837099/79fd136a-9ebb-11e6-9776-cb5f645eb566.png)

я сторонник все-таки ставить `{}` в if всегда, если не в одну строку
![image](https://cloud.githubusercontent.com/assets/10474869/19837106/a1a37ba2-9ebb-11e6-84dd-bdbeaf4c578a.png)

это то, что сразу заметила. внимательно не смотрела 😉

**Comment by trofivan** [comment]
@krambertech спасибо за развёрнутый ответ, поправлю. 
И странно, что у тебя не работает фильтр, у меня в Chrome на винде всё нормально отрабатывает.
![image](https://cloud.githubusercontent.com/assets/1439599/19839692/3e294d70-9f08-11e6-9730-273d990af73f.png)
![image](https://cloud.githubusercontent.com/assets/1439599/19839695/4b0a51ec-9f08-11e6-8345-fe56d8d8334f.png)
![image](https://cloud.githubusercontent.com/assets/1439599/19839697/5a9e4d5c-9f08-11e6-8645-11036d738d2f.png)

**Comment by trofivan** [comment]
@krambertech а в чём преимущество использования .map перед .forEach в моём коде?
С .map получается такая же конструкция, что и с forEach, или я что-то не так понял?
![image](https://cloud.githubusercontent.com/assets/1439599/19853068/cc683166-9f88-11e6-8ac8-2bc54310be0b.png)
![image](https://cloud.githubusercontent.com/assets/1439599/19853074/df154e16-9f88-11e6-9b86-5d9718f5fb63.png)

**Comment by trofivan** [comment]
@krambertech ты в каком браузере тестировала и на какой ОС? Хочу проверить у себя почему переключение вкладок не работает. Проверил на винде в Хроме, IE, FireFox - всё работает.

**Comment by krambertech** [comment]
@trofivan почитай документацию map и forEach и используй их по назначению. map проходится по массиву и **возвращает новый массив**, forEach же просто проходится по массиву. 

И ты сейчас мутируешь свой массив по ссылке, это всегда плохо :)

**Comment by krambertech** [comment]
@trofivan macOS, Chrome 54.0.2840.71 (64-bit)

**Comment by dmitry-shishkin** [comment]
У меня получился вот такой список задач: https://codepen.io/shugich/pen/NapxyZ
Он же на Гитхабе: https://github.com/shugich/react-todo

Я хотел повешать сначала добавление задачи на onsubmit для формы, так как мне это кажется правильным и логичным. Но в итоге я так и не разобрался как отменять стандартное действие. `event.preventDefault()` тут не срабатывает.

**Comment by trofivan** [comment]
@shugich  не знаю, почему у Вас не работал вариант с .preventDefault(), может с аргументом ошиблись. Вот переписал: https://codepen.io/trofivan/pen/YrZbBm?editors=0010
И если вы используете контролируемую форму и храните текст в state, то при добавлении его в базу тоже берите его из state, а не завязывайтесь на элемент.

**Comment by dmitry-shishkin** [comment]
Странно, наверное я что-то не так делал. Спасибо большое. И за замечания про использование стейта, это так очевидно, а я почему-то упустил :-(
