### ISSUE TITLE
Документация по JavaScript Google API

### ISSUE THREAD

**Issue by maxttor** [krambertech/react-essential-course#52]
На Google Tasks API нет информации по API на JavaScript. Т.е. совершенно не ясно, как формируются запросы:
gapi.client.tasks.tasks.insert
gapi.client.tasks.tasks.list
gapi.client.tasks.tasks.update

В видео уроках, вы их просто вставляете из буфера обмена, не поясняя откуда их брать...

**Comment by krambertech** [comment]
Они есть в Reference

https://developers.google.com/google-apps/tasks/v1/reference/

**Comment by krambertech** [comment]
Точно так же работает и в JavaScript API
