### ISSUE TITLE
Проблемы с кодом в третьем уроке. Ломается

### ISSUE THREAD

**Issue by andriishch** [krambertech/react-essential-course#54]
Урок номер № 3 :  валиться сборка на <NotesApp /> в src/main.js ... В какой части ломается код? Или уже так не пишут на последних версиях ?
Линтер пишет вот такое :
2.     Use the function form of 'use strict'.	'use strict';
3	'require' was used before it was defined.	var ReactDOM = require('react-dom');
4	'require' was used before it was defined.	var React = require('react');
5	'require' was used before it was defined.	var NotesApp = require('./components/NotesApp.jsx');
Браузер и командная строка ругаются так : 
D:\Projects\www\200517>webpack
Hash: 48f76d9d7c6a1ac2c056
Version: webpack 2.5.1
Time: 3860ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.34 kB       0  [emitted]  main
   [0] ./src/main.js 699 bytes {0} [built] [failed] [1 error]

ERROR in ./src/main.js
Module build failed: SyntaxError: D:/Projects/www/200517/src/main.js: Unexpected token (9:4)

   7 |
   8 | ReactDOM.render(
>  9 |  <NotesApp />,
     |     ^
  10 |     document.getElementById('mount-point')
  11 | );

**Comment by krambertech** [comment]
Cклонировала, установила зависимости и запустила. Все ок

Вебпак при сборке ругается на JSX синтаксис.  У вас точно в `.babelrc` подключен react-preset?

**Comment by andriishch** [comment]
Здравствуйте Екатерина ! Хочу поблагодарить Вас за полноту и обьемность курса !!!По ошибке. Следовал в точности инструкциям в уроке. Простой пример с hello vasya работает, сложный ломается. Полностью клонировал папки build, src; webpack.config json.config не трогал. Точно такие же ошибки. О react-present впервый раз слышу :-(


Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: Kateryna <notifications@github.com> Дата: 07.06.2017  3:28  (GMT+02:00) Кому: krambertech/react-essential-course <react-essential-course@noreply.github.com> Копия: andriishch <andriishch@gmail.com>, Author <author@noreply.github.com> Тема: Re: [krambertech/react-essential-course] Проблемы с кодом в третьем уроке. Ломается (#54) 
Cклонировала, установила зависимости и запустила. Все ок
Вебпак при сборке ругается на JSX синтаксис.  У вас точно в .babelrc подключен react-preset?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/krambertech/react-essential-course","title":"krambertech/react-essential-course","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/krambertech/react-essential-course"}},"updates":{"snippets":[{"icon":"PERSON","message":"@krambertech in #54: Cклонировала, установила зависимости и запустила. Все ок\r\n\r\nВебпак при сборке ругается на JSX синтаксис.  У вас точно в `.babelrc` подключен react-preset?"}],"action":{"name":"View Issue","url":"https://github.com/krambertech/react-essential-course/issues/54#issuecomment-306651552"}}}

**Comment by krambertech** [comment]
Прости, я совсем упустила твой ответ :( Думаю, уже неактуально. Но если актуально - переоткрой :)
