### ISSUE TITLE
Сообщение об ошибке

### ISSUE THREAD

**Issue by romanson-god** [krambertech/react-essential-course#55]
А как понять, где синтаксическая ошибка? В браузере пишет такое "Uncaught SyntaxError: embedded: Unexpected token (19:14)" и дальше стек по browser.js.
А что и где я неверно написал непонятно.

**Comment by krambertech** [comment]
Скорее всего, babel увидел что-то незнакомое, часто такое бывает с `<` в JSX. Coветую использовать babel не через browserjs, тогда ошибки всегда будут более понятными :)
