### ISSUE TITLE
react js выдает ошибку В уроке "Contact Search" - 'displayedContacts' of null

### ISSUE THREAD

**Issue by ONESucH** [krambertech/react-essential-course#59]
Создал <a href="https://gist.github.com/ONESucH/1c06f9130c8fa152b06c1bc77b2c3154">Gist файл</a>, для просмотра.
Ошибка:
TypeError: Cannot read property 'displayedContacts' of null

У вас в уроках всё хорошо, проблема Во Мне я возможно что-то не подключил(чего не понимаю), можете помочь?

**Comment by MakarovMax** [comment]
Попробуйте вот так:

import React, { Component } from 'react';

const arr = [
  {
    id: 1,
    name: 'Василий',
    phone: '+7 900 000 00 00',
    img: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAABBVBMVEX////SOi7Zrq7/zMy11c6eJBrROS2/v7/RkJDONirKMiagJh3JMSWdKyLGLiKkKiHitbW9b2ryoZ6nKR/44d/TQDX88/K30cr4+Pizx8DVRjrvubXPlpbTPzOzwrvli4T66ef8wsHVZ2DXoaGnQDjN497s7OzWenTDNivaXVPq8/HcZ17q1tTWTULsraj88O/gd2/Ozs7xw7/nl5Hsrqn/3NzLnp3Y2Ni/mZDVc23Zqanqo5300c7WfHfYVErCkIelSUGse3PDgn2wWVKyuLGmOjLbYljGioWzKR+tYFrMcmvBsa+0gHy4jIm6o6K+oJi2TEGmVUzvl5O+YlrVjYjPs63jwcEma2UEAAAI/ElEQVR4nNXde3sSRxQHYNgGSRoRUgGRS7NCDFLYQEyqhoRtlAJqmtpq6vf/KN1LyN5m57rnzPr7K48+PtnXmTMzO+wOhQJQmlcnw/HItqx2o922LHs0nh1e1qF+G1DqJ2OrSIw1mp1PdV8eZ64O22TENm37MP8tM71kKPw0rDNT96XSYh7yKPz0+q91X25amgIML6OO7ksm5rIh6HAp+WuVui3OcDP+XfeVR3Mmx3Bz2NR98UHqI3mHM7fkpn+d91QcbqO0dBPcNGeKDCejHMyQslUeTVt793rNNZNz5FKvo6NaHkEOdTpOMmM4melzXGbpcCS6Bq9M28OT6HF0snZoqpOr7Oo8iIaxq57VuBsN+sq+mck8mEwDezWcwbqEHBt3MZz5gBUEdeiqS9wNcgezTNaAjmLbRHMAdiw3aJ3LhBl5g2Ct6RnbPhfKEBvHcUW/ioWhPsXgTPD0KWRhGAtlSBtjMqE3iOMw5uo1hNEk1AZxHYahXiUITVKn/f6h5zDmKZ+OCOQEHEIbsu4dWVQJ+MDVpCxOHhyGoT71Q88llEk95DAGyvUOPb2n/1dfGOHcqUJ6sOWeXupRh2EMVSWwi+DUDaC4wzD6ihDYvpXWs5IOZUkDsm9NBRzKEshxK2Uri+xQneEhN7nIs2Gawxm7VPa+RoAQ4kds6Q7D2FVZrMAVSZP06/oUh7PsUigUuCIhreDpDrd7STcK3Fr+XMLhNMqFZKUMwSDJT9M5HE4Gcv1rDQZJ3FPxOZx0+xKtYoFB4oMWt8NtlQvxBTHYsBUrWxGHk/lC9AEJsE/fo91D0OE1y1Boq+gKyBGdRiQcnmUx5u5jUBOJGfodr0ZyDi/dRZ9rcoG6JQlBXlUOFCBey9wN+zajbaAgwe3hq4oQpJaa+eXd4qK/ti3rflMjUobn0BDHIQKp/cSXF06+YkDMkAMC4uYXxBrxHD80pBlyoEDA1vGNwIECgZoQ3SXK1oECMaEg48CBAgF77GkYODAgcMv4uwoqZAwGmeNC4Da2JrgQqIm9UGjhQsBG30JhiQlpAD6r+QETAlfrhUINE3IGCGliQgBLpFD4hgdpQzoKAzwI3IapmykeBPiD9m9YkDbwg/I1LAj00+WtFRIE/GWlOxwI5Gzox6yiQBCez1xgQDAez6xXESAoT2Mv4CGQH7EH8asEFIL0BPOZC/kEA/mKM2T5af4DB3EfEumhvfD62ulcSzgI5I1ILMNK5RoGMnOGXsTXEZ3OdQQDGRd7oDdU8VxVKzAQG/sNvrPqAATS6OM6CoX+BgLywkI/kKe5gID8ouFQjgkERMtBAxAQLUeLfAeA6HDw9y1+iJ5ja5rZQzSdIcbbt/ghehyFetYQbQciZQ3RdhwSZ7nzQvSdUNXKFqLxuEC+JuGE6DwyjK9JOCFaz2/kGrj4IJrPcOOZS/ggmk9wm2YFMfU6uOqdB5KDwwHZnYsHkoOjAZu1DCC5OHHWVIfk4Cw9N6wxmAnJQYH4YRQ8C5IbB0vCgOTIwZDQIblyFF7eyEJqz37TffGhvNx59kYOMn++s5MfycudHUcyF4e8GDiO/EhchytJ29ZOhXS6niMvEt/hSrrkRkmDDLaOfEi2DleyS2wUMqSzGzjyIAkcnoREIUE6uxGHfknY4Ut2B/EOloSc78YduiVRx71ktzugQTqDXYJDryTu2EqillpCQXLolCQdgcTtY4P5PIC86HQG3e1fkRz6JCRHRLK96m43/ie/Ev+pJgnZQZIkZCkOPZI0B1uS7tAhSXc4knhX4nbgS2gOhoTqwJbQHVQJw4ErYTkoEqYDU8J2pEo4HDs7SM85mcaG53KIEi7Hf69NeMWkuzxaVY4kJVyOTdsezU5A9+wmG1ex74RL8jwu4XN4L4pZdh/qe8jqbltU9+8jIylzO9z0LKddzKwVrdpBSCEnEXP47TI6zPR5IbO79HuUikTc4b0PY49Pstqqn3y4XsUV4hIuxx9xh9fF1mdZVMvkw1GiMSQk0g431kiZQmEISZQcbg8bKX3L3XRzVCmVShQJ8UYvKeFzPEqHOJT1pfTHc8Z1Zb9UUpe8X/7J4yg+okqK1lhuBJscrHwGVXLNlryvVldsietgSIr2ULxUWl2vV2UgcRwckneegyVpjESPmJ58WpUikZZ4DqZk62BJitbMFHHUriulUiaSewdDEjiYksaav1Jam6A6FCUPDqok7GBKijbvawDTg0RzyEpCjmr1KE3y7lE0LInF9xWK9SXZISGJOBwJef6MtgePpM1TKJNrQreSk8QcKZKkgy1pjJnjMM0hKEk4iJIvBAdb0mNJ6A4hCcFBkJAdyhKT4RCQEB0JyRcyg0NSHFPqZLpkOaiSZ2xHTPLl0d6erKQ3Sx27WinjLq/k30Bym+aISFyHvKSRegjBhsfBJbnd3+eQfOnt7alI2ikz4/cVl4NDcuv+zJRsHfIS8jfymtecDqbk1v+ZInkecchL1qR9iQN2ofNJbrfbRukSZ4QLO6QlPUKZ1PgKhC25fcqRf95FHNKS5PfxNvk7FlXy9Mnjx49/TsteeiQl6/gY3BXoWBSJ58CU9GK3jNMjQQdZcu/AlNjRet+INghR8uDAlEQmk6Z4gxAkIQeiJPLdnHOJBklKwg6KRIJClYTPUFlKOWKSqANPEnoDfiI0h6RI4g40SSO4M9nIOkKSj0kIliQod8HJkCT5+OSJNsnDAT0TuVIPS1yHNsnDgTADFYcn8R3aJNvTWz+pQUoPDl2S7UmIK0VI4NAkuT9WrK5UIlGHHknP9CDfs3Tokfin9HQzdWiR+Gv5g2wdOiSHSgutNIcGyUx1Xic78CX+3C51L+LlaYoDWpKg+EflSy990x3YkrZSi9AcyBJbZYVCd+BKPnuQdyAOVMkbD/J2BeJAlFhvPcjxXzAOPMnm2F81loVnEj4HlmRdvl/GH98IjsC8DpIk+w0v6+Z4e697+reYhNuBIbH+Pn3YfGiVb0QmEwEHvGR9Uw49St8ql/9agTiAJdamXI68EtA6LZdvl0fV7B1wkp79+U25fBp/teHYofx4OT0uJHP89geznL4NMf4Ho9hKU8+zv1oAAAAASUVORK5CYII='
  },
  {
    id: 2,
    name: 'Петя',
    phone: '+7 700 000 00 00',
    img: 'https://addons.cdn.mozilla.net/user-media/userpics/0/0/45.png?modified=1490992702'
  },
  {
    id: 3,
    name: 'Володя',
    phone: '+7 300 000 00 00',
    img: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAPDxMQDxMWFRAXFRYaEhAXDxUXFxYWFxcXFxUeFhcYHSggGx4lHBgVLTEhJysrLi4uGCAzODMuNystLisBCgoKDg0OGhAQGislHyIwLS0tKy0tLS0tLS0tLS0tLS0tLS0tLS0tKy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tK//AABEIAMgAyAMBEQACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAAAwIEBQYHAQj/xABJEAABAwICBQgGBgcFCQAAAAABAAIDBBEFIQYSEzFBByJRYXGBkaEUMkJSsdEjYnKSwcIVM1SCk5TwJFVzsuEIQ0VTorPD0uL/xAAbAQEAAwEBAQEAAAAAAAAAAAAAAQIDBAUGB//EADARAAICAQMCAwcEAwEBAAAAAAABAhEDBBIxIUETIlEFFDJSYXGRI4Gh8EKx0eEG/9oADAMBAAIRAxEAPwDuKAIAgCAIAgCAIAgCAIC3qa2KL9ZIxn2ntb8SockuWSot8ItRj9Fe3pUF+j0iP5qviQ9UW8Ofoy8p6qOQXje146WvDvgrJp8FWmuSZSQEAQBAEAQBAEAQBAEAQBAEAQBAEAQBAEBpekPKDDA7Y0rfSJt3NPMB7Rm49Q8VzZNTGPSPVnRj07fWXQwvoGN4hzp5fR4j7AJZl9hmZ/eKwcsk+XRsvChwrJ6fk1gGcs0j3cSNVoPiHHzVPDJ8Z9id3J5RdMvbtB/6qHAeKyxqOTuMHWp55GOG4uAd5t1SFTgusl8lDZ8aw7MO9JhG8EmTLv547rhaR1E49yrxY5/Q2fRrTmmrCI3/AEM+7ZuOTj9R3HsNiuzHqIz6cM5smCUOvKNqW5gEAQBAEAQBAEAQBAEAQBAEAQBAUSyNY0ueQGgEucTYADeSUboJWc1xXG6nGZjS0N2Ug/WS5jWHS7jY8G8ePVwZMzyPbHg7YY1jW6XJtOj2jNPRN+ibeS3OmcLuPTboHUFaGNIpPI5Ga1VptM7PC1VaJTI3BZtFkyFwWUkXRE8LGSNEa5pFoxDVAuA1JuEgG8/WHHt3ql0aJlroxpZNSSiixI5bo6gncNw1ncWn3t449Xdg1P8AjI58uBPzROjrvOMIAgCAIAgCAIAgCAIAgCAIAgOc6dYpJW1LcLpTlcbd3C4zsepozPXlwXBqcrk/Dj+52YIKK3s2vA8KipIWwxDIb3cXO4k9amEUlRWcm3Zk2hbxRiyTVWlFbKHBZyRZELllI0RC9YyLohesZGiIJFiy6MDpHhDKuItOTxcxv6D8jxVbosme8nGkDzfD6nKaO+yJOZa3e3rLeHV2L1NLm3Lazl1GKvMjfV2HKEAQBAEAQBAEAQBAEAQBAY3SPExSUks/FreaOlxyb5kLPLPZByL447pJGn8nWGFsTquTOWYkhx36t/xdc9wXm4l3Z2ZX2RurV0xMGStK2izNkmsr2VoocVSTLIhcspGiIXrGRdEL1jI0RBIsWXRaSqjLGmaVxOp5oq6HJ7XDWPWPVJ7RcHuVsc3GVolrcqZ1TCq5tTBHOz1XtBA6OkdxuO5e9GSkk0eW1ToulJAQBAEAQBAEAQBAEAQBAaDyr1BcympW75JCT3Wa2/e8+C4ddLoonVpV1bNko4WxsbG31WtDR2AWCwiXZdNK2TM2iQOWiZVoq1lbcRR4XKrZKRG4rNsskQuKyky6InlYyZoi3kKzZctJSqMkw+OQbWCRnS027RmPMBVslF3yTV5fTSQE5xvu37L8/iD4r2dHK8dehxamNTv1N6XUc4QBAEAQBAEAQBAEAQBAc502OtjNGzgGxm3XtHn8oXl61/qJfQ7tP8DNtaVmmS0StctUyjRWHK6ZWj3XU7iKPC5Q2TRQ5yo2WSI3FZtlkiJxWTZdFtK5ZssWkrlVklnKVVkmH5KpNWsmj4Fh8nD/AFXp6B/Evsc2rXDOqr0TjCAIAgCAIAgCAIAgCAIDnOnQ1MXo5DuLWNv2SOv/AJgvK13TIn9Du03wNG0tcsEy7RIHLRMq0VByspFaPdZTuFHhco3CikuVWyyRQ5yzbLJEEj1RssW0jlVklrK5VZJaSuVWSYfkubeue4btR3hf/UL0/Z6+J/Y5dW+EdZXpHGEAQBAEAQBAEAQBAEAQGi8qtIdjBUt9aKSxPQHWIJ72jxXn+0IeVS9Dq0surRkKGrEsbJG7nNBHeLrz0zpou2vV0yKKg5TuIo91lO4UC5RuFFBeobJoie9Vskgkeq2SW0j1DBbSPVWSYvGKnZwvdxsQO05BVLF3yTUdjLL9UNH7xv8AlHiva0MNuK/U8/USuf2OjLsMAgCAIAgCAIAgCAIAgCAscbw8VVNLA722kA9Dt7T3EA9yzywU4OL7loS2yTOdaH1zma9JLlJG51mnovzh3G/ivAVxbi+x6b69UbU2RXsgwGLyVMlfT08VQ6COSOQgiNjrvZzj6w90rt0uOE07KTltjZkG6M1p/wCJSfy0S6/dcfoc/vP0JBopWn/iUn8tEnuuP0HvP0PTojWf3lJ/KxJ7rj9B7z9CN2iVZ/eUn8tEo91x+g95foRO0Tq/7xk/lok90xeg95foYfAZpb1LJZTLs6h8bXlrWkhlgcm9ZXm6uEYTqJ1wdpMv5HrkLGr6RVW0e2FvA3d2/wCg+Ktjg8k1FdyJS2xbZ1HQ3DfRqNjSLOdznDt3D7oHmvo4pRSSPLbt2ZxSQEAQBAEAQBAEAQBAEAQBAcu5StjTVkU8MrW1LvXhvzshk4jgCMs7X6815OvxJPfHnv8A9OjBqIp+HJ88GQwjFWVEYe3I+03iD8lwqVna0QaQQyObHUQC9RA/XjHvjc9n7zfgurTZfDn14KyjuVM2vAcYhrYRNC643OafWY7i144Ef1kvZTs86UXF0zLMUlSUoCF6A13SzH20UVm86pflBCMy5x3Ej3RxKrOairZpjxubNWwik9HgbGTd+bpHe89xu49eZ8l8/myeJNyPSSot8XxIQty9c+qPxPUsWySLk8wtlbUF7nBzWG8gvmTfIW6yN/QF6+gwqMd75f8AB52XURyPbF9EdgXomIQBAEAQBAEAQBAEAQBAEBznTzlBMLzRYd9JVE6rpGjW1HHLVYPaf5DrO7ny5q8seTkzaivLDkxOA6A6l6vFHa8ub3Mc67W8SZXH1j5dq5njfMjGOGvNMhgw+V+0rcPadi11tnxI4kN4t6t4uO7hnp3W+HB6uj1yyKp/szI4Zjsc1geZJ7pO/sPFYKdnpUe1OGDa7enkdT1HGSO1nf4jDk8dq6sWqnj6corKKkqZdw6Q4rDYObTVDRxBfFI7rO9o7l2x18HyjB6aPYuDptXWt+jhfp9PZbw1Ff37F6lfdfqWVRjuLTC2tT07T7TGOkkHVz+asp+0Ir4UXjporksaTD2ROdK5zpJ3evPI7Weeq53DqC8/NqJ5OTdRS6It67GA06kXPkOQAzF+7eeoLncizpK2W1PSshqIziLbiUWzN2tLsm646Mj2fDowQT80jxtV7RjJ7Icd3/exJjehVTQP9Nwlzhq5mIG7mjjq++36p816KhKPWJ58sMoeaBuWgOnceJN2Uto6sDNnsyAbzHfzbvHWurFlU+j5OrBnWTo+Tc1sdAQBAEAQBAEAQBAEAQHOeU/TR1P/AGCiJNU+we5ubow7c1tvbdfuB6SLYZsleVcnJqM1eWPJdcnOhLKBgnqAHVjhmd4iB9lp6ek9wy3xixqPV8k4MKh1fJRpPK/EasYbTEiJnOq5RwA9kf1v7Cscv6k/Dj+5nmbyz8OPHczOA0rad89MwarWljmD6paG+RarKO1OIjHa5RRZY3orT1RLrbOX32jefrN3H49a4smnjP6M2wazJi6cr0NPq6aso3Oa14lYxus613BrfrXzGXAFcksGSPHU9TDrcWV7eGW9PpUHD1Wnra/8Fk21yjtcJLlE50kb7h8Qo3laLOp0otuDQeGs+/lkpW6XCLrHJ9i8hwuqqH7Od+yBF9Ug3I6gMj3lTLFkSto8zP7Rx4+ker/g2rCcDgps2C7+Mjs3d3R3KlHi6jWZc/xPp6HsmDx18s0cg5gja3W4teSXAjrH4r09Hi3QdkYMSmmmV6E4hJDI/Daz9fF+qef95Hwt02Hl2FdmCTi/Dlyjo08nF+HPlGD5SNDS1xxLD7snYdeVjMibZ67LbnDiOO/fvtlh13RIz4eu+PJsfJ1pi3E4NWSwqowNq3drDcHtHQeI4HtC1xZNy+ptgzeIuvJt61NwgCAIAgCAIAgCAwOm2kTcNo3zmxkPNhYfakO7uGZPUFSctqszy5NkbOfcl2Aule7FKu7pHucYi7eSSdeQ9d7gd/UuWPNs48ELe9m86U436JTFzM5n82Fu86x426vkOKnLl2R6cm2bLsj057Emh2DCip7OznedaZ+8lx4X42+NzxV8ENkevL5LYMeyP1fJdYzTPDm1MIvIy4cz/mRn1m9o3hXyRvqhli/ijyv5RSatj6d88R1gGuNuILRezhwKxcE1aMWlKO5FrhOHhsDCc3PAc93vOcLm/iix9C+LHUUcm0lwU4fWOhAtBJd9OeAF+ez90+RC87WYa86P0T2Dr/GxeHJ9V/f5/wClivPPoKRnNAsENbV7Z4vT05y6Hz7x90Z9tl6mjweXc+58l/8ARa+o+BB88/3+PydNxbDQ+Fx3OaC5juIc0XHwXbLFcWfE5MacWYz068ceqNaWQDUjG8kjyA6V5EMDnPajzoxcnSNjwagFPEGk3kJLpHdLjv8Al3L3scFjjSPWxY1CNGD05wt0jG1dPlUwHWaRvcwZuHX027RxWGoi2t8eUY6mDa3x5RksHxVtXTsmb7Q5zfdcMnDxVoZFONl4ZFOKkcs0ww+TBcQjxCjFonOzZ7IcfXYfquF7dGdtwWd7ZWjlmnjnuidiwXFI6ynjqITdkjQR0g7iD1g3B7F2p2rPQjJSVovVJYIAgCAIAgCAIDiOntY7FsZjoYz9DE7UJHAjOd3aLW/d61y5pWzz88t+Tb6HT6ONsTGxsFmNaGtaOAAsFkmbLoa9RD07EXTOzgp+bGOBk4nxz7mrKL8TJfZGEf1Ml9kbk167EzsTJGvV0y1mPrsGjlLnsc6KRwIc5hsHA5c9u5yq4J9TKeGMuq6P6F/QQbOJkZOtqtDda1r2FhktIqlRrBbYpehg9O9HBiFG5jMqhnPgd9dvC/Q4XHeDwVMuNTi0duh1L02ZTX7nFIXSTakUTT6RI8RtjO8PvY36LZ3XhQ07eXYz9Aza6ENP41netGsEioKWOmjz1RzncXvOb3HtN/Je/GKiqPznPmebI5y7l9WxbSJ8YOrrNLda17XFrqZdVRhJWmiywrCYaUcwEvtYyON3EdHUOoLOEIw4KQxxhwXrnqzZayF71Rshs07Df7BXvp90E/Pi6Gv4j4juauOL8PI49mccf08jj2ZlNI8NZWU0lO/2m80+64ZtPcbLVs1mtyo0vkZxp0FRNhs+Vy50YPsyMykb3gX/AHT0rfDLsRpZ03BnYV0HaEAQBAEAQBAY7SLEhSUc9Qf93G5wHS63NHe6w71DdKys5bYtnH+SajLnz1b83X1A48S7nyHt9XxK8/I+x5uLmzfMfxAw073N9c81na7o7Bc9yxnPbE0yT2xLjR6iFNTsj9q13/aO/wCXctMS2xotijtjRlmvWyZtZI16umSmSB6smWsrEincTZ7tFO4Wa5RaJU8OJy4i313t5sdsmSOyleOtwA8XdOVVFKW4656ycsCwvhf1f37GxmRW3HJZSZFG4WUF6iyLKHPVHIrZE56q2VbNf0tpTJBtGfrIjrsPHL1vn3LmzK42uxhnVxtdi8oa0TRMkHtDMdB4jxupU7VkxnuVnLNNtagxeOriyuWSjo1mmzx32z+0t8Uu5k3tmpHeqSobLGyRmbXtDmnqcLhdx6hKgCAIAgCAIDQOWyu2eF7MHOWZjSPqtvIfNrVTJwc+pdQoxPJ3Bs8Oi6Xlzj3uIHkGrzMsvOzkhwX9Z9PWRR+xGNd3bw/L4lYN7ppehV+aaXobC166EzoTJWvV0ybJGvV0y1lYkU7ibKxIrbibPdop3E2e7RNws82ibhZSZFG4iykyKu4iyNz1VsiyNz1VsrZDI64sdyo2VbMBgZ2T5ac7mu1mfZP9DxXPB03Ewxum4mtcrMGtBDLxbIW9z23/ACBdOB+ZoTN+5LK/b4VBc3LLsJ+ycvIhelHg9HC7gjbVY0CAIAgCAIDk3L9NaOjZwLpj90Rj8ypM5NW+iL3RghtDT/4MZ8Wgrxsj87+5ypkuCZmSY73uy7B/Xks8b5ZGPuzMtetkzayRr1dMmyQSKyZayQSK24myoSKdxNnu0U7hY10sWNom4WUmRRuIspMijcLKHSKrkVsjc9VbIsic9UbK2YavOpUxyjc7mu/D4+Swk6kmYy6STMNykZ0Dup7D52/FdOmf6hLZluQue9FMz3ZAfvA/JetDg79M/IdLVjcIAgCAIAgOP/7QG+h7Kj/wqkjj1XYucKlth8P+BEPFjQvAzPzy+7OJvoZSgGpG0dXxzURdItHoi8a9aJl7JGvV1ItZIJFZSJsrD1Nk2VCRW3E2e7RNwsbRNwsbRNwspMijcLKS9RZFlBkVWyLI3PVWyLI3PVWyrZj8VGtH1gghZTfQznwa/p7JrYc49Jj/AMwXRpHeVC7MnyCn6Cp+0z4OXtR4PQ03wHVVY6AgCAIAgCA4/wD7QLT/AGE8Ppx/2VDOTVdijAZhJQ09t2oxv3RqnzC+c1KrLJfU8+RnmvVUyyZK16smWska9WTJsrD1ay1lYkVtxNlQkU7hZ7tFO4mxtE3CxtE3CykyKNxFlJkUbiLKTIq2RZG56q2RZG56q2RZBM64I6lRsq2anp1MG0Gqd7ntA7iXfgunQK8v2RETP8go+gqPtM/MvdR6Wm+A6qpOgIAgCAIAgNB5aMHNRhplYLvgeH9eoRqv8Lg9jUMNRG436HNeT3FhY0zzncuj/MPx8V5HtLA1WVfueZNdzemvXlplbJGvVky1kgerJk2ViRWsmysSKdxNlW0U7ibPdop3CxtE3CxtE3CykyKNwspMijcRZSZFFkWRl6q2RZQ56q2Vsic9UbIs5tp7iglmELDzY763W87/AAH4r2/Z2Bxhvff/AEXguh1rkcwwwUJc4WLyPK5Pm8juXonq4o7YpG/IaBAEAQBAEBRNE17Sx4Ba4EOaRcEEWII7EB81adaMy4RW2ZfYk69NL1X3E+83cenI8UcVJUzzsuPa/obLo1pKyqaGPIbOBm3g7rb8l89q9HLC7XWP+vucko0bAHrisrZIJFZSJsrEincWsqEituFlQkU7ibG0TcLPdolizzaJuFnhkTcLKTIo3EWUmRV3EWUGRVciLKC9RZFmqaVaUNgBhgN5jkXDdH/9dXBejotC8j3z+H/f/heML6s17QzAZK2obYXGtlf2nb8+obyV73B24Me52+D6VwyibTwshZuaLX6TvJ7zdQdxdIAgCAIAgCAIDF6R4FBiFO6nqG3ac2u4tdwLT0oRKKkqZ896X6EVeGSXsXw3uyZoPde24q3R9GcWTC48cFOEaazRANnG1b717PHfuPf4rzs/suE+sHT/AIOV40+Da6HSijmtaQMd7r+b5nLzXlZNBnx/439upm4NGYilDhdpBHSCCPJcrTj0ZUk11Fiz3XU7ibG0U7hZ7tE3CzzaJuFnmuo3EWeayixZFNUNYLvcGjpLgPipjGUuiVgwtfpbSRXs/aO91gv/ANW7zXZi9nZ58qvv/bLKDZqWMaYTz3ZH9Ew8AbuPa75L1tP7Nx4+sur/AI/BrHGkVaNaIz1kjQWOsdzfaPb7o6yu9s6seBvqzv2iOjEdBGAADKRYkbmjob1dfFUOxJJUjYEJCAIAgCAIAgCAICOogZI0skaHNO9pFwUBz7STknpKgl9Odk88OF+35gqVJozlijI55i3JXXwklg129IBP+W58QFbcYPTvszXJdHa2F3qEHqeAfC4Kl7XyUeCfoehuJN3GoHZI/wDArN4MD5ivwingv5T3bYn71R956r7tp/kX4RHgv5RtsT96o+89PdtP8i/CHgv5RtsT96o+89PdtP8AIvwh4L+UbbE/eqPvPT3bT/Ivwh4L+UbbE/eqPvPT3bT/ACR/CHgv5Sl0WIvyJnPbI78SrLDhXEV+ET4MvQ8j0cq5Dm2xPFzwfgSVpcVwXWCfobBhXJpWTEXa63UwgfffYKNxotP6s6Bo7yVRwkOmIB6Bzn/eOTe4KrbZvHHGPB0HDsNhpm6kLA0cTxPaTmVBcu0AQBAEAQBAEAQBAEAQBAEBTJG12TgCOggFAWr8JpjvgiPbCz5ICP8AQdJ+zxfwm/JAP0HSfs8X8JvyQD9B0n7PF/Cb8kA/QdJ+zxfwm/JAP0HSfs8X8JvyQFbcHpRugi/gs+SAuYoGM9RrW9jQPggJEAQBAEAQBAEAQH//2Q=='
  }
];

const Contact = (props) => {
  return (
    <div>
      <img src={this.props.img} alt='user' />
      <span>Name - {this.props.name}</span>
      <span>Phone - {this.props.phone}</span>
    </div>
  )

};

class Content extends Component {
  constructor(props) {
    super(props);
    this.state = {
      displayedContacts = arr,
    }
  }

  handleSearch(event) {
    const searchJquery = event.target.value.toLowerCase();
    const displayedContacts = arr.filter((el) => {
      const searchValue = el.name.toLowerCase();
      return searchValue.indexOf(searchJquery) !== -1;
    });

    this.setState({
      displayedContacts,
    });
  };

  render() {
    return (
      <div className="App-pages">
        <input type="text" onChange={this.handleSearch.bind(this)} placeholder="Поиск по друзьям" />
        {
          this.state.displayedContacts.map(function (el) {
            return <Contact
              key={el.id}
              name={el.name}
              phone={el.phone}
              img={el.img}
            />
          })
        }
      </div>
    )
  }
};

export default Content;

**Comment by ghost** [comment]
Попробуйте вот так:
https://codepen.io/makarov_max/pen/ZXKbzx?editors=0011

**Comment by ONESucH** [comment]
Error: line 39 - displayedContacts = arr,
Выдаёт отшибку из-за того что у нас объект, сменил "=" на ":" Ошибка пропала, появилась другая
проблема с "const Contact = (props) => " props не передаётся undefined.
Попробовал весь ваш код вставить в свой(на тест), всё равно ошибка висит.
Спасибо за помощь

**Comment by oleg-tgn** [comment]
@ONESucH думаю ошибка в создании `class Content extends Component {`

в уроке он создавался как  var` ContactsList = React.createClass({`
а у вашего класса видимо нет метода реакта this.setState вот state и остался пустым

**Comment by ONESucH** [comment]
попробовал добавить setState в свой класс, но у меня всё равно props не видит мои данные
Вот мой gist(файл)
https://gist.github.com/ONESucH/33546190bd2ad44c96c6dc3e93edc22d

**Comment by lozinsky** [comment]
Привет. Можешь поизучать: https://codesandbox.io/s/l74z5v68vl.
В твоем gist, в компоненте:
```js
const Contact = (props) => {
    return (
        <div>
            <img src={this.props.img} alt='user' />
            <span>Name - {this.props.name}</span>
            <span>Phone - {this.props.phone}</span>
        </div>
    )
};
```
Идет обращение к this, хотя это просто stateless компонент, и по сути функция, у которой this является undefined'ом, если используешь модули, или объектом window, если скрипт просто подключен на страницу. Так что правильно будет так:
```js
const Contact = (props) => {
    return (
        <div>
            <img src={props.img} alt='user' />
            <span>Name - {props.name}</span>
            <span>Phone - {props.phone}</span>
        </div>
    )
};
```
В компоненте:
```js
class Content extends Component {
    constructor(props) {
        super(props);
        this.state = {
            displayedContacts: arr,
        };
        this.setState({
            displayedContacts:arr
        })
    }
}
```
Не нужно вызывать setState, т.к. state уже задан выше.

**Comment by ONESucH** [comment]
Спасибо всем за помощь) 
Высылаю последний gist(рабочий вариант), может пригодиться кому-нибудь ;D
<a href="https://gist.github.com/ONESucH/f6599c1387ac4ff9f82af58fad750e89">Gist файл</a>
Всем удачи!
