### ISSUE TITLE
Как изящно решить третью задачу из первого урока?

### ISSUE THREAD

**Issue by baeron** [krambertech/react-essential-course#60]
Решил этот пример вот так
`        var Contact = React.createClass({
            
            getInitialState: function() {
                return {
                    visible: false
                };
            },

            isOpened: function(e) {
                var temp = null;
                if(this.state.visible){
                    temp = false;
                } else {
                    temp = true;
                }
               this.setState({visible: temp});

            },
            render: function() {
                var img = this.props.image,
                    name = this.props.name,
                    phone = this.props.phoneNumber,
                    info = this.props.info,
                    visible = this.state.visible; // считываем значение переменной из состояния компонента

                if(visible){
                    return (
                    <li className="contact" onClick={this.isOpened}>
                        <img className="contact-image" src={img} width="60px" height="60px" />
                        <div className="contact-info">
                            <div className="contact-name"> {name} </div>
                            <div className="contact-number"> {phone} </div>
                            <div className={'contact-number'}>{info}</div>
                        </div>
                    </li>
                    );
                } else {
                    return (
                    <li className="contact" onClick={this.isOpened}>
                        <img className="contact-image" src={img} width="60px" height="60px" />
                        <div className="contact-info">
                            <div className="contact-name"> {name} </div>
                            <div className="contact-number"> {phone} </div>
                        </div>
                    </li>
                    );
                }
            }
        });`

Но сам понимаю, что это убогое решение.

**Comment by krambertech** [comment]
Привет! Вообще идея правильная. Вот как можно улучшить:
 - Переименовать `visible` на `opened`, оно более четко отражает суть
 - Плюс, я бы переименовала метод `isOpened`. Лучше чтобы функции отражали то, что они делают, поэтому можно назвать `toggleOpened` или `handleToggleOpened`. Так как я сторонник именовая обработчиков с `handle`, то выбираю второй вариант, но это дело вкуса :) 
 - Можно использовать [тернарный оператор](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/%D0%A3%D1%81%D0%BB%D0%BE%D0%B2%D0%BD%D1%8B%D0%B9_%D0%BE%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80), так все выглядит лаконичнее + мы избегаем лишних переменных
- В методе `render` тоже прямо внутри jsx можно использовать тернарный оператор (или оператор И `&&`) для того, чтобы показать или скрыть `info`
- Необязательно писать `px` для величин, т.к. они используются по умолчанию, поэтому лучше их не писать
- Ну, и я не сторонник `var` через зяпятую ;)

Вот что выходит:

```jsx
var Contact = React.createClass({
    getInitialState: function() {
        return {
            opened: false
        };
    },

    handleToggleOpened: function() {
        this.setState({ opened: !this.state.opened });
    },
    
    render: function() {
        var img = this.props.image;
        var name = this.props.name;
        var phone = this.props.phoneNumber;
        var info = this.props.info;
        var opened = this.state.opened;

        return (
            <li className="contact" onClick={this.handleToggleOpened}>
                <img 
                    className="contact-image" 
                    src={img} 
                    width={60} 
                    height={60} 
                />
                <div className="contact-info">
                    <div className="contact-name">{name}</div>
                    <div className="contact-number">{phone}</div>
                    {
                        opened
                        && <div className="contact-info">{info}</div>
                    }
                </div>
            </li>
        );
    }
});
```

А если еще использовать возможность ES6+, то может выйти так:

```jsx
class Contact extends React.Component {
    state = {
        opened: false
    }

    handleToggleOpened = () => {
        this.setState({ opened: !this.state.opened });
    }
    
    render() {
        const {
            img,
            name,
            phoneNumber,
            info
        } = this.props;
        const { opened } = this.state;

        return (
            <li className="contact" onClick={this.handleToggleOpened}>
                <img 
                    className="contact-image" 
                    src={img} 
                    width={60} 
                    height={60} 
                />
                <div className="contact-info">
                    <div className="contact-name">{name}</div>
                    <div className="contact-number">{phoneNumber}</div>
                    {
                        opened
                        && <div className="contact-info">{info}</div>
                    }
                </div>
            </li>
        );
    }
}
```
