### ISSUE TITLE
Вопрос по 2 заданию

### ISSUE THREAD

**Issue by AnastasiaTischenko** [krambertech/react-essential-course#61]
Привет) можешь глянуть код? что то не так с синтаксисом, думаю проблема в рендере но не понимаю как исправить. если это возможно можете подсказать?
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="https://fb.me/react-0.14.3.js"></script>
<script src="https://fb.me/react-dom-0.14.3.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser.js"></script>
</head>
<body>
    <div id="content"></div>
    
    <script type="text/babel">

        var Output = React.createClass({
            render: function(){
                return (
                    <p>Hello {this.props.name}</p>
                );
            }
        })
        
        var Hello = React.createClass({
            getInitialState: function(){
              return {
                  name: ""
              };  
            },
            
            handleNameChange: function(event) {
                this.setState({
                    name: event.target.value,
                });
            },
            
            render: function(){
                return (
                    <div>
                        <input type="text" onChange={this.handleNameChange} value={this.state.name}/>
                        <div>{
                            <Output {this.name}/>
                            }
                        </div>
                     </div>   
                );
            }
        });

 
        ReactDOM.render(
            <Hello />,
            document.getElementById('content')
        );
    </script>
</body>
</html>

**Comment by sgromkov** [comment]
Вместо `<Output {this.name}/>` попробуйте `<Output name={this.state.name} />`. Пропущен `state` и забыли присвоить его в `name`.

**Comment by sgromkov** [comment]
Подправленный код: https://codepen.io/anon/pen/bYgVYG
