### ISSUE TITLE
environment - task 3

### ISSUE THREAD

**Issue by olecium** [krambertech/react-essential-course#64]
Здравствуйте, подскажите пожалуйста как примерно должно выглядеть приложение для учета расходов. Должен ли быть отдельный столбец в таблице  с выводом остатка?

**Comment by krambertech** [comment]
Привет!

Например, так:

![image](https://user-images.githubusercontent.com/10474869/38297589-a4a0217a-37fd-11e8-9252-5aab6eb20be8.png)

(только поменяй + и - местами)

**Comment by olecium** [comment]
спасибо большое)
