### ISSUE TITLE
Вопрос по домашнему заданию

### ISSUE THREAD

**Issue by Petrovi430** [krambertech/react-essential-course#65]
Добрый день.  Смотрю  Ваш курс по Реакт. В домашнем задании где нужно добавить строку поиска я реализовал поиск заметок, но после того как один раз найти заметки перестают работать функции удаления заметки и добавления новой заметки. Не подскажете, как исправить даный функционал. Заранее благодарен.

**Comment by krambertech** [comment]
Привет! Сбрось код, без него сложно сказать что не так

**Comment by Petrovi430** [comment]
[03-notes-app.zip](https://github.com/krambertech/react-essential-course/files/1932052/03-notes-app.zip)

**Comment by Petrovi430** [comment]
Привет. Я уже разобрался, когда делал to do list. У меня не правильный подход был по реализации фильтрации данных.  Спасибо, что откликнулись)
