### ISSUE TITLE
Урок 3: Окружение - Задание 2 : Отображение статей

### ISSUE THREAD

**Issue by maplemap** [krambertech/react-essential-course#9]
Катерин, привет.
Вопрос насчет поиска статей.
Если пойти далее этого задания и, к примеру, не только отображать статьи согласно поиску, но и подсвечивать запрос (т.е. оборачивать в span) в тексте найденных статей. Есть варианты в какую сторону идти?

**Comment by krambertech** [comment]
Ну, тут 2 варианта. 

Ты можешь либо в самом главном компоненте менять текст заметок (например, ставить ** и ** вокруг нужных слов), а в компоненте Note использовать Markdown (с переопределенными стилями) для подсветки.

Либо 2й вариант просто передавать в компонент Note слова для подсветки и обрабатывать уже там. Есть, например библиотека [react-highlight-words](https://www.npmjs.com/package/react-highlight-words).

Оба варианта имеют право на жизнь, но мне второй кажется проще и очевиднее, что ли.

**Comment by maplemap** [comment]
Спасибо за варианты, первый и второй пробовал, после твоего совета все-таки реализовал с помощью второго.
Особая благодарность за react-highlight! Это шикарно!
